name: 'Citation'

on:
  push:
    paths:
      - CITATION.cff

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate Citation
    runs-on: ubuntu-24.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Validate
      uses: dieghernan/cff-validator@4c19ae163bc427f66a5b69ddd4487cfbf5bec48d # v3
      with:
        install-r: true
