Kalman: fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments > Class Template Reference
fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments > Class Template Reference
Kalman filter.
#include <kalman.hpp>
Public Types
Public Member Types
using value_type = Type
The type of the filtered data elements.
using state = typename implementation::state
Type of the state estimate vector X.
using output = typename implementation::output
Type of the observation vector Z.
using input = typename implementation::input
Type of the control vector U.
using estimate_uncertainty = typename implementation::estimate_uncertainty
Type of the estimated correlated variance matrix P.
using process_uncertainty = typename implementation::process_uncertainty
Type of the process noise correlated variance matrix Q.
using output_uncertainty = typename implementation::output_uncertainty
Type of the observation noise correlated variance matrix R.
using state_transition = typename implementation::state_transition
Type of the state transition matrix F.
using output_model = typename implementation::output_model
Type of the observation transition matrix H.
using input_control = typename implementation::input_control
Type of the control transition matrix G.
using gain = typename implementation::gain
Type of the gain matrix K.
using innovation = typename implementation::innovation
Type of the innovation vector Y.
using innovation_uncertainty = typename implementation::innovation_uncertainty
Type of the innovation uncertainty matrix S.
Public Member Functions
Public Member Functions
constexpr kalman ()=default
Constructs a Kalman filter without configuration.
constexpr kalman (const kalman &other)=default
Copy constructs a filter.
constexpr kalman (kalman &&other) noexcept=default
Move constructs a filter.
constexpr auto operator= (const kalman &other) -> kalman &=default
Copy assignment operator.
constexpr auto operator= (kalman &&other) noexcept -> kalman &=default
Move assignment operator.
constexpr ~kalman ()=default
Destructs the kalman filter.
Public Characteristics Member Functions
constexpr auto x () const -> state
Returns the state estimate vector X.
constexpr void x (const state &value)
Sets the state estimate vector X.
constexpr void x (state &&value)
Sets the state estimate vector X.
constexpr void x (const auto &value, const auto &...values)
Sets the state estimate vector X.
constexpr void x (auto &&value, auto &&...values)
Sets the state estimate vector X.
constexpr auto z () const -> output
Returns the observation vector Z.
constexpr auto u () const -> input
Returns the control vector U.
constexpr auto p () const -> estimate_uncertainty
Returns the estimated covariance matrix P.
constexpr void p (const estimate_uncertainty &value)
Sets the estimated covariance matrix P.
constexpr void p (estimate_uncertainty &&value)
Sets the estimated covariance matrix P.
constexpr void p (const auto &value, const auto &...values)
Sets the estimated covariance matrix P.
constexpr void p (auto &&value, auto &&...values)
Sets the estimated covariance matrix P.
constexpr auto q () const -> process_uncertainty
Returns the process noise covariance matrix Q.
constexpr void q (const process_uncertainty &value)
Sets the process noise covariance matrix Q.
constexpr void q (process_uncertainty &&value)
Sets the process noise covariance matrix Q.
constexpr void q (const auto &value, const auto &...values)
Sets the process noise covariance matrix Q.
constexpr void q (auto &&value, auto &&...values)
Sets the process noise covariance matrix Q.
constexpr void q (const auto &callable)
Sets the process noise covariance matrix Q function.
constexpr void q (auto &&callable)
Sets the process noise covariance matrix Q function.
constexpr auto r () const -> output_uncertainty
Returns the observation noise covariance matrix R.
constexpr void r (const output_uncertainty &value)
Sets the observation noise covariance matrix R.
constexpr void r (output_uncertainty &&value)
Sets the observation noise covariance matrix R.
constexpr void r (const auto &value, const auto &...values)
Sets the observation noise covariance matrix R.
constexpr void r (auto &&value, auto &&...values)
Sets the observation noise covariance matrix R.
constexpr void r (const auto &callable)
Sets the observation noise covariance matrix R function.
constexpr void r (auto &&callable)
Sets the observation noise covariance matrix R function.
constexpr auto f () const -> state_transition
Returns the state transition matrix F.
constexpr void f (const state_transition &value)
Sets the state transition matrix F.
constexpr void f (state_transition &&value)
Sets the state transition matrix F.
constexpr void f (const auto &value, const auto &...values)
Sets the state transition matrix F.
constexpr void f (auto &&value, auto &&...values)
Sets the state transition matrix F.
constexpr void f (const auto &callable)
Sets the state transition matrix F function.
constexpr void f (auto &&callable)
Sets the state transition matrix F function.
constexpr auto h () const -> output_model
Returns the observation transition matrix H.
constexpr void h (const output_model &value)
Sets the observation transition matrix H.
constexpr void h (output_model &&value)
Sets the observation transition matrix H.
constexpr void h (const auto &value, const auto &...values)
Sets the observation, measurement transition matrix H.
constexpr void h (auto &&value, auto &&...values)
Sets the observation, measurement transition matrix H.
constexpr void h (const auto &callable)
Sets the observation, measurement transition matrix H function.
constexpr void h (auto &&callable)
Sets the observation, measurement transition matrix H function.
constexpr auto g () const -> input_control
Returns the control transition matrix G.
constexpr void g (const input_control &value)
Sets the control transition matrix G.
constexpr void g (input_control &&value)
Sets the control transition matrix G.
constexpr void g (const auto &value, const auto &...values)
Sets the control transition matrix G.
constexpr void g (auto &&value, auto &&...values)
Sets the control transition matrix G.
constexpr void g (const auto &callable)
Sets the control transition matrix G function.
constexpr void g (auto &&callable)
Sets the control transition matrix G function.
constexpr auto k () const -> gain
Returns the gain matrix K.
constexpr auto y () const -> innovation
Returns the innovation vector Y.
constexpr auto s () const -> innovation_uncertainty
Returns the innovation uncertainty matrix S.
constexpr void transition (const auto &callable)
constexpr void transition (auto &&callable)
constexpr void observation (const auto &callable)
constexpr void observation (auto &&callable)
Public Filtering Member Functions
constexpr void operator() (const PredictionArguments &...arguments, const auto &...input_u, const auto &...output_z)
Runs a step of the filter.
constexpr void update (const auto &...output_z)
Updates the estimates with the outcome of a measurement.
constexpr void predict (const PredictionArguments &...arguments, const auto &...input_u)
Produces estimates of the state variables and uncertainties.
Private Types
Private Member Types
using implementation = internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments... >
Implementation details of the filter.
Private Attributes
Private Member Variables
implementation filter
Encapsulates the implementation details of the filter.
Detailed Description
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments>
class fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >
Kalman filter.
A Bayesian filter that uses multivariate Gaussians. Applicable for unimodal and uncorrelated uncertainties. Kalman filters assume white noise, propagation and measurement functions are differentiable, and that the uncertainty stays centered on the state estimate. The filter updates estimates by multiplying Gaussians and predicts estimates by adding Gaussians. Design the state (x, P), the process (F, Q), the measurement (z, R), the measurement function H, and if the system has control inputs (u, B). Designing a filter is as much art as science.
Template Parameters
Type The type template parameter of the value type of the filter.
State The type template parameter of the state vector x. State variables can be observed (measured), or hidden variables (infeered). This is the the mean of the multivariate Gaussian.
Output The type template parameter of the measurement vector z.
Input The type template parameter of the control u.
Transpose The customization point object template parameter of the matrix transpose functor.
Symmetrize The customization point object template parameter of the matrix symmetrization functor.
Divide The customization point object template parameter of the matrix division functor.
Identity The customization point object template parameter of the matrix identity functor.
PredictionArguments The variadic type template parameter for additional prediction function parameters. Time, or a delta thereof, is often a prediction parameter. The parameters are propagated to the function objects used to compute the process noise Q, the state transition F, and the control transition G matrices.
Note
This class could be usable in constant expressions if std::function could too. The polymorphic function wrapper was used in place of function pointers to enable default initialization from this class, captured member variables.
Todo:
Is this filter restricted to Newton's equations of motion? That is only a discretized continuous-time kinematic filter? How about non-Newtonian systems?
Would it be beneficial to support initialization list for characteristis?
Symmetrization support might be superflous. How to confirm it is safe to remove?
Would we want to support smoothers?
How to add or associate constraints on the types and operation to support compilation and semantics?
Which constructors to support?
Is the Kalman filter a recursive state estimation, confirm terminology?
Prepare support for std::format?
Prepare support for larger dataset recording for graphing, metrics of large test data to facilitate tuning.
Support filter generator? Integration? Reflection in C++...
Compare performance of general filter with its equivalent generated?
Support ranges operator filter?
Support mux pipes https://github.com/joboccara/pipes operator filter?
Reproduce Ardupilot's inertial navigation EKF and comparison benchmarks in SITL (software in the loop simulation).
Definition at line 118 of file kalman.hpp.
Member Typedef Documentation
estimate_uncertainty
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> using fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::estimate_uncertainty = typename implementation::estimate_uncertainty
Type of the estimated correlated variance matrix P.
Also known as .
Examples
rocket_altitude.cpp, and vehicule_location.cpp.
Definition at line 152 of file kalman.hpp.
gain
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> using fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::gain = typename implementation::gain
Type of the gain matrix K.
Definition at line 176 of file kalman.hpp.
implementation
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> using fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::implementation = internal::kalman<State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments...> private
Implementation details of the filter.
Definition at line 125 of file kalman.hpp.
innovation
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> using fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::innovation = typename implementation::innovation
Type of the innovation vector Y.
Definition at line 179 of file kalman.hpp.
innovation_uncertainty
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> using fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::innovation_uncertainty = typename implementation::innovation_uncertainty
Type of the innovation uncertainty matrix S.
Definition at line 182 of file kalman.hpp.
input
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> using fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::input = typename implementation::input
Type of the control vector U.
Definition at line 147 of file kalman.hpp.
input_control
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> using fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::input_control = typename implementation::input_control
Type of the control transition matrix G.
Also known as B.
Examples
rocket_altitude.cpp.
Definition at line 173 of file kalman.hpp.
output
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> using fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::output = typename implementation::output
Type of the observation vector Z.
Also known as Y or O.
Definition at line 144 of file kalman.hpp.
output_model
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> using fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::output_model = typename implementation::output_model
Type of the observation transition matrix H.
Also known as the measurement transition matrix or C.
Examples
vehicule_location.cpp.
Definition at line 168 of file kalman.hpp.
output_uncertainty
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> using fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::output_uncertainty = typename implementation::output_uncertainty
Type of the observation noise correlated variance matrix R.
Examples
vehicule_location.cpp.
Definition at line 158 of file kalman.hpp.
process_uncertainty
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> using fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::process_uncertainty = typename implementation::process_uncertainty
Type of the process noise correlated variance matrix Q.
Examples
rocket_altitude.cpp, and vehicule_location.cpp.
Definition at line 155 of file kalman.hpp.
state
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> using fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::state = typename implementation::state
Type of the state estimate vector X.
Examples
rocket_altitude.cpp.
Definition at line 139 of file kalman.hpp.
state_transition
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> using fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::state_transition = typename implementation::state_transition
Type of the state transition matrix F.
Also known as the fundamental matrix, propagation, , or A.
Examples
rocket_altitude.cpp, and vehicule_location.cpp.
Definition at line 163 of file kalman.hpp.
value_type
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> using fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::value_type = Type
The type of the filtered data elements.
Definition at line 136 of file kalman.hpp.
Constructor & Destructor Documentation
kalman() [1/3]
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> constexpr fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::kalman () inline constexpr default
Constructs a Kalman filter without configuration.
Complexity
Constant.
kalman() [2/3]
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> constexpr fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::kalman (const kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments > & other) inline constexpr default
Copy constructs a filter.
Constructs the filter with the copy of the contents of the other filter.
Parameters
other Another filter to be used as source to initialize the elements of the filter with.
Complexity
Constant.
kalman() [3/3]
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> constexpr fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::kalman (kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments > && other) inline constexpr default noexcept
Move constructs a filter.
Move constructor. Constructs the filter with the contents of the other filter using move semantics (i.e. the data in other filter is moved from the other into this filter).
Parameters
other Another filter to be used as source to initialize the elements of the filter with.
Complexity
Constant.
~kalman()
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> constexpr fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::~kalman () inline constexpr default
Destructs the kalman filter.
Complexity
Constant.
Member Function Documentation
f() [1/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr auto fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::f inline constexpr
Returns the state transition matrix F.
Returns
The state transition matrix F.
Complexity
Constant.
Definition at line 1139 of file kalman.hpp.
{
  return filter.f;
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::f().
Referenced by fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::f().
f() [2/7]
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::f (auto && callable) inline constexpr
Sets the state transition matrix F function.
Parameters
callable The moved target Callable object (function object, pointer to function, reference to function, pointer to member function, or pointer to data member) that will be bound to the prediction arguments and called by the filter to compute the state transition matrix F function on prediction steps.
Complexity
Constant.
Definition at line 605 of file kalman.hpp.
  {
    filter.transition_state_f = std::forward<decltype(callable)>(callable);
  }
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::filter, and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::transition_state_f.
f() [3/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::f (auto && value, auto &&... values) inline constexpr
Sets the state transition matrix F.
Parameters
value The first moved initializer used to set the state transition matrix F.
values The second and other moved initializers to set the state transition matrix F.
Complexity
Constant.
Definition at line 1179 of file kalman.hpp.
{
  filter.f =
      std::move(state_transition{ std::forward<decltype(value)>(value),
                                  std::forward<decltype(values)>(values)... });
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::f().
f() [4/7]
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::f (const auto & callable) inline constexpr
Sets the state transition matrix F function.
Parameters
callable The copied target Callable object (function object, pointer to function, reference to function, pointer to member function, or pointer to data member) that will be bound to the prediction arguments and called by the filter to compute the state transition matrix F function on prediction steps.
Complexity
Constant.
Definition at line 588 of file kalman.hpp.
  {
    filter.transition_state_f = callable;
  }
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::filter, and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::transition_state_f.
f() [5/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::f (const auto & value, const auto &... values) inline constexpr
Sets the state transition matrix F.
Parameters
value The first copied initializer used to set the state transition matrix F.
values The second and other copied initializers to set the state transition matrix F.
Complexity
Constant.
Definition at line 1169 of file kalman.hpp.
{
  filter.f = state_transition{ value, values... };
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::f().
f() [6/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::f (const state_transition & value) inline constexpr
Sets the state transition matrix F.
Parameters
value The copied state transition matrix F.
Complexity
Constant.
Definition at line 1149 of file kalman.hpp.
{
  filter.f = value;
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::f().
f() [7/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::f (state_transition && value) inline constexpr
Sets the state transition matrix F.
Parameters
value The moved state transition matrix F.
Complexity
Constant.
Definition at line 1159 of file kalman.hpp.
{
  filter.f = std::move(value);
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::f().
g() [1/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr auto fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::g inline constexpr
Returns the control transition matrix G.
Returns
The control transition matrix G.
Complexity
Constant.
Definition at line 1243 of file kalman.hpp.
{
  return filter.g;
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::g().
Referenced by fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::g().
g() [2/7]
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::g (auto && callable) inline constexpr
Sets the control transition matrix G function.
Parameters
callable The moved target Callable object (function object, pointer to function, reference to function, pointer to member function, or pointer to data member) that will be bound to the prediction arguments and called by the filter to compute the control transition matrix G on prediction steps.
Complexity
Constant.
Definition at line 761 of file kalman.hpp.
  {
    filter.transition_control_g = std::forward<decltype(callable)>(callable);
  }
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::filter, and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::transition_control_g.
g() [3/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::g (auto && value, auto &&... values) inline constexpr
Sets the control transition matrix G.
Parameters
value The first moved initializer used to set the control transition matrix G.
values The second and other moved initializers to set the control transition matrix G.
Complexity
Constant.
Definition at line 1283 of file kalman.hpp.
{
  filter.g =
      std::move(input_control{ std::forward<decltype(value)>(value),
                               std::forward<decltype(values)>(values)... });
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::g().
g() [4/7]
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::g (const auto & callable) inline constexpr
Sets the control transition matrix G function.
Parameters
callable The copied target Callable object (function object, pointer to function, reference to function, pointer to member function, or pointer to data member) that will be bound to the prediction arguments and called by the filter to compute the control transition matrix G on prediction steps.
Complexity
Constant.
Definition at line 744 of file kalman.hpp.
  {
    filter.transition_control_g = callable;
  }
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::filter, and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::transition_control_g.
g() [5/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::g (const auto & value, const auto &... values) inline constexpr
Sets the control transition matrix G.
Parameters
value The first copied initializer used to set the control transition matrix G.
values The second and other copied initializers to set the control transition matrix G.
Complexity
Constant.
Definition at line 1273 of file kalman.hpp.
{
  filter.g = input_control{ value, values... };
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::g().
g() [6/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::g (const input_control & value) inline constexpr
Sets the control transition matrix G.
Parameters
value The copied control transition matrix G.
Complexity
Constant.
Definition at line 1253 of file kalman.hpp.
{
  filter.g = value;
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::g().
g() [7/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::g (input_control && value) inline constexpr
Sets the control transition matrix G.
Parameters
value The moved control transition matrix G.
Complexity
Constant.
Definition at line 1263 of file kalman.hpp.
{
  filter.g = std::move(value);
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::g().
h() [1/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr auto fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::h inline constexpr
Returns the observation transition matrix H.
Returns
The observation, measurement transition matrix H.
Complexity
Constant.
Definition at line 1191 of file kalman.hpp.
{
  return filter.h;
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::h().
Referenced by fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::h().
h() [2/7]
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::h (auto && callable) inline constexpr
Sets the observation, measurement transition matrix H function.
Parameters
callable The moved target Callable object (function object, pointer to function, reference to function, pointer to member function, or pointer to data member) that will be bound to the prediction arguments and called by the filter to compute the observation, measurement transition matrix H on update steps.
Complexity
Constant.
Definition at line 684 of file kalman.hpp.
  {
    filter.observation_state_h = std::forward<decltype(callable)>(callable);
  }
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::filter, and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::observation_state_h.
h() [3/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::h (auto && value, auto &&... values) inline constexpr
Sets the observation, measurement transition matrix H.
Parameters
value The first moved initializer used to set the observation, measurement transition matrix H.
values The second and other moved initializers to set the observation, measurement transition matrix H.
Complexity
Constant.
Definition at line 1231 of file kalman.hpp.
{
  filter.h =
      std::move(output_model{ std::forward<decltype(value)>(value),
                              std::forward<decltype(values)>(values)... });
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::h().
h() [4/7]
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::h (const auto & callable) inline constexpr
Sets the observation, measurement transition matrix H function.
Parameters
callable The copied target Callable object (function object, pointer to function, reference to function, pointer to member function, or pointer to data member) that will be bound to the prediction arguments and called by the filter to compute the observation, measurement transition matrix H on update steps.
Complexity
Constant.
Todo:
Understand why Cland Tidy doesn't find the out-of-line definition.
Definition at line 667 of file kalman.hpp.
  {
    filter.observation_state_h = callable;
  }
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::filter, and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::observation_state_h.
h() [5/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::h (const auto & value, const auto &... values) inline constexpr
Sets the observation, measurement transition matrix H.
Parameters
value The first copied initializer used to set the observation, measurement transition matrix H.
values The second and other copied initializers to set the observation, measurement transition matrix H.
Complexity
Constant.
Definition at line 1221 of file kalman.hpp.
{
  filter.h = output_model{ value, values... };
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::h().
h() [6/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::h (const output_model & value) inline constexpr
Sets the observation transition matrix H.
Parameters
value The copied observation transition matrix H.
Complexity
Constant.
Definition at line 1201 of file kalman.hpp.
{
  filter.h = value;
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::h().
h() [7/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::h (output_model && value) inline constexpr
Sets the observation transition matrix H.
Parameters
value The moved observation transition matrix H.
Complexity
Constant.
Definition at line 1211 of file kalman.hpp.
{
  filter.h = std::move(value);
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::h().
k()
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr auto fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::k inline constexpr
Returns the gain matrix K.
Returns
The gain matrix K.
Complexity
Constant.
Definition at line 1295 of file kalman.hpp.
{
  return filter.k;
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::k().
Referenced by fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::k().
observation() [1/2]
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::observation (auto && callable) inline constexpr
Definition at line 820 of file kalman.hpp.
  {
    filter.observation = std::forward<decltype(callable)>(callable);
  }
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::filter, and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::observation.
observation() [2/2]
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::observation (const auto & callable) inline constexpr
Definition at line 812 of file kalman.hpp.
  {
    filter.observation = callable;
  }
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::filter, and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::observation.
operator()()
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::operator() (const PredictionArguments &... arguments, const auto &... input_u, const auto &... output_z) inline constexpr
Runs a step of the filter.
Predicts and updates the estimates per prediction arguments, control input, and measurement output.
Parameters
arguments Optional prediction parameters passed through for computations of prediction matrices.
input_u Optional control parameters. Types must be compatible with the Input types. The parameter pack types must always be explicitely defined per the
output_z Observation parameters. Types must be compatible with the output type. The parameter pack types are always deduced per the greedy matching rule.
Note
Called as k(...); with prediction values and output values when the filter has no input parameters. The input type list is explicitely empty. Otherwise can be called as k.template operator()<input1_t, input2_t, ...>(...); with prediction values, input values, and output values. The input type list being explicitely specified. A lambda can come in handy to reduce the verbose call `const auto kf{ &k { k.template operator()<input1_t, input2_t, ...>(args...); } };then called askf(...);`.
Todo:
Consider if returning the state vector X would be preferrable? And if it would be compatible with an ES-EKF implementation? Or if a fluent interface would be preferrable?
Understand why the implementation cannot be moved out of the class.
Definition at line 860 of file kalman.hpp.
  {
    filter.update(output_z...);
    filter.predict(arguments..., input_u...);
  }
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::filter, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::predict(), and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::update().
operator=() [1/2]
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> constexpr auto fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::operator= (const kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments > & other) -> kalman &=default inline constexpr default
Copy assignment operator.
Destroys or copy-assigns the contents with a copy of the contents of the other filter.
Parameters
other Another filter to be used as source to initialize the elements of the filter with.
Returns
The reference value of this implicit object filter parameter, i.e. *this.
Complexity
Constant.
operator=() [2/2]
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> constexpr auto fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::operator= (kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments > && other) -> kalman &=default inline constexpr default noexcept
Move assignment operator.
Replaces the contents of the filter with those of the other filter using move semantics (i.e. the data in other filter is moved from the other into this filter). The other filter is in a valid but unspecified state afterwards.
Parameters
other Another filter to be used as source to initialize the elements of the filter with.
Returns
The reference value of this implicit object filter parameter, i.e. *this.
Complexity
Constant.
p() [1/5]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr auto fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::p inline constexpr
Returns the estimated covariance matrix P.
Returns
The estimated correlated variance matrix P.
Complexity
Constant.
Definition at line 979 of file kalman.hpp.
{
  return filter.p;
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::p().
Referenced by fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::p().
p() [2/5]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::p (auto && value, auto &&... values) inline constexpr
Sets the estimated covariance matrix P.
Parameters
value The first moved initializer used to set the estimated covariance matrix P.
values The second and other moved initializers to set the estimated covariance matrix P.
Complexity
Constant.
Todo:
Consider if a fluent interface would be preferrable? In addition to constructors? Same question for all characteristics set methods.
Definition at line 1019 of file kalman.hpp.
{
  filter.p = std::move(
      estimate_uncertainty{ std::forward<decltype(value)>(value),
                            std::forward<decltype(values)>(values)... });
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::p().
p() [3/5]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::p (const auto & value, const auto &... values) inline constexpr
Sets the estimated covariance matrix P.
Parameters
value The first copied initializer used to set the estimated covariance matrix P.
values The second and other copied initializers to set the estimated covariance matrix P.
Complexity
Constant.
Definition at line 1009 of file kalman.hpp.
{
  filter.p = std::move(estimate_uncertainty{ value, values... });
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::p().
p() [4/5]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::p (const estimate_uncertainty & value) inline constexpr
Sets the estimated covariance matrix P.
Parameters
value The copied estimated covariance matrix P.
Complexity
Constant.
Definition at line 989 of file kalman.hpp.
{
  filter.p = value;
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::p().
p() [5/5]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::p (estimate_uncertainty && value) inline constexpr
Sets the estimated covariance matrix P.
Parameters
value The moved estimated covariance matrix P.
Complexity
Constant.
Definition at line 999 of file kalman.hpp.
{
  filter.p = std::move(value);
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::p().
predict()
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::predict (const PredictionArguments &... arguments, const auto &... input_u) inline constexpr
Produces estimates of the state variables and uncertainties.
Implements the total probability theorem.
Parameters
arguments Optional prediction parameters passed through for computations of prediction matrices.
input_u Optional control parameters. Types must be compatible with the Input types. The parameter pack types are always deduced per the greedy matching rule.
Todo:
Consider whether this method needs to exist or if the operator() is sufficient for all clients.
Consider if returning the state vector X would be preferrable? And if it would be compatible with an ES-EKF implementation? Or if a fluent interface would be preferrable?
Definition at line 1335 of file kalman.hpp.
{
  filter.predict(arguments..., input_u...);
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::predict().
Referenced by fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::predict().
q() [1/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr auto fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::q inline constexpr
Returns the process noise covariance matrix Q.
Returns
The process noise correlated variance matrix Q.
Complexity
Constant.
Definition at line 1031 of file kalman.hpp.
{
  return filter.q;
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::q().
Referenced by fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::q().
q() [2/7]
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::q (auto && callable) inline constexpr
Sets the process noise covariance matrix Q function.
Parameters
callable The moved target Callable object (function object, pointer to function, reference to function, pointer to member function, or pointer to data member) that will be bound to the prediction arguments and called by the filter to compute the process noise covariance matrix Q on prediction steps.
Complexity
Constant.
Definition at line 446 of file kalman.hpp.
  {
    filter.noise_process_q = std::forward<decltype(callable)>(callable);
  }
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::filter, and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::noise_process_q.
q() [3/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::q (auto && value, auto &&... values) inline constexpr
Sets the process noise covariance matrix Q.
Parameters
value The first moved initializer used to set the process noise covariance matrix Q.
values The second and other moved initializers used to set the process noise covariance matrix Q.
Complexity
Constant.
Todo:
Don't we need to reset functions or values when the other is set?
Definition at line 1075 of file kalman.hpp.
{
  filter.q = std::move(
      process_uncertainty{ std::forward<decltype(value)>(value),
                           std::forward<decltype(values)>(values)... });
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::q().
q() [4/7]
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::q (const auto & callable) inline constexpr
Sets the process noise covariance matrix Q function.
Parameters
callable The copied target Callable object (function object, pointer to function, reference to function, pointer to member function, or pointer to data member) that will be bound to the prediction arguments and called by the filter to compute the process noise covariance matrix Q on prediction steps.
Complexity
Constant.
Todo:
Understand why Cland Tidy doesn't find the out-of-line definition.
Definition at line 428 of file kalman.hpp.
  {
    filter.noise_process_q = callable;
  }
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::filter, and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::noise_process_q.
q() [5/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::q (const auto & value, const auto &... values) inline constexpr
Sets the process noise covariance matrix Q.
Parameters
value The first copied initializer used to set the process noise covariance matrix Q.
values The second and other copied initializers to set the process noise covariance matrix Q.
Complexity
Constant.
Todo:
Don't we need to reset functions or values when the other is set?
Definition at line 1064 of file kalman.hpp.
{
  filter.q = std::move(process_uncertainty{ value, values... });
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::q().
q() [6/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::q (const process_uncertainty & value) inline constexpr
Sets the process noise covariance matrix Q.
Parameters
value The copied process noise covariance matrix Q.
Complexity
Constant.
Todo:
Don't we need to reset functions or values when the other is set?
Definition at line 1042 of file kalman.hpp.
{
  filter.q = value;
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::q().
q() [7/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::q (process_uncertainty && value) inline constexpr
Sets the process noise covariance matrix Q.
Parameters
value The moved process noise covariance matrix Q.
Complexity
Constant.
Todo:
Don't we need to reset functions or values when the other is set?
Definition at line 1053 of file kalman.hpp.
{
  filter.q = std::move(value);
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::q().
r() [1/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr auto fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::r inline constexpr
Returns the observation noise covariance matrix R.
The variance there is in each measurement.
Returns
The observation noise correlated variance matrix R.
Complexity
Constant.
Definition at line 1087 of file kalman.hpp.
{
  return filter.r;
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::r().
Referenced by fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::r().
r() [2/7]
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::r (auto && callable) inline constexpr
Sets the observation noise covariance matrix R function.
Parameters
callable The moved target Callable object (function object, pointer to function, reference to function, pointer to member function, or pointer to data member) that will be called by the filter to compute the observation noise covariance matrix R on prediction steps.
Complexity
Constant.
Definition at line 528 of file kalman.hpp.
  {
    filter.noise_observation_r = std::forward<decltype(callable)>(callable);
  }
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::filter, and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::noise_observation_r.
r() [3/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::r (auto && value, auto &&... values) inline constexpr
Sets the observation noise covariance matrix R.
Parameters
value The first moved initializer used to set the observation noise covariance matrix R.
values The second and other moved initializers to set the observation noise covariance matrix R.
Complexity
Constant.
Definition at line 1127 of file kalman.hpp.
{
  filter.r = std::move(
      output_uncertainty{ std::forward<decltype(value)>(value),
                          std::forward<decltype(values)>(values)... });
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::r().
r() [4/7]
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::r (const auto & callable) inline constexpr
Sets the observation noise covariance matrix R function.
Parameters
callable The copied target Callable object (function object, pointer to function, reference to function, pointer to member function, or pointer to data member) that will be called by the filter to compute the observation noise covariance matrix R on prediction steps.
Complexity
Constant.
Todo:
Understand why Cland Tidy doesn't find the out-of-line definition.
Definition at line 510 of file kalman.hpp.
  {
    filter.noise_observation_r = callable;
  }
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::filter, and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::noise_observation_r.
r() [5/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::r (const auto & value, const auto &... values) inline constexpr
Sets the observation noise covariance matrix R.
Parameters
value The first copied initializer used to set the observation noise covariance matrix R.
values The second and other copied initializers to set the observation noise covariance matrix R.
Complexity
Constant.
Definition at line 1117 of file kalman.hpp.
{
  filter.r = output_uncertainty{ value, values... };
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::r().
r() [6/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::r (const output_uncertainty & value) inline constexpr
Sets the observation noise covariance matrix R.
Parameters
value The copied observation noise covariance matrix R.
Complexity
Constant.
Definition at line 1097 of file kalman.hpp.
{
  filter.r = value;
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::r().
r() [7/7]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::r (output_uncertainty && value) inline constexpr
Sets the observation noise covariance matrix R.
Parameters
value The moved observation noise covariance matrix R.
Complexity
Constant.
Definition at line 1107 of file kalman.hpp.
{
  filter.r = std::move(value);
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::r().
s()
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr auto fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::s inline constexpr
Returns the innovation uncertainty matrix S.
Returns
The innovation uncertainty matrix S.
Complexity
Constant.
Definition at line 1315 of file kalman.hpp.
{
  return filter.s;
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::s().
Referenced by fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::s().
transition() [1/2]
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::transition (auto && callable) inline constexpr
Definition at line 804 of file kalman.hpp.
  {
    filter.transition = std::forward<decltype(callable)>(callable);
  }
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::filter, and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::transition.
transition() [2/2]
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::transition (const auto & callable) inline constexpr
Definition at line 796 of file kalman.hpp.
  {
    filter.transition = callable;
  }
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::filter, and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::transition.
u()
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> constexpr auto fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::u () const -> input inline constexpr
Returns the control vector U.
Returns
The control vector U.
Complexity
Constant.
Todo:
Implement and test.
update()
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::update (const auto &... output_z) inline constexpr
Updates the estimates with the outcome of a measurement.
Implements the Bayes' theorem. Combine one measurement and the prior estimate.
Template Parameters
output_z Observation parameters. Types must be compatible with the output type.
Todo:
Consider whether this method needs to exist or if the operator() is sufficient for all clients.
Consider if returning the state vector X would be preferrable? And if it would be compatible with an ES-EKF implementation? Or if a fluent interface would be preferrable?
Definition at line 1325 of file kalman.hpp.
{
  filter.update(output_z...);
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::update().
Referenced by fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::update().
x() [1/5]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr auto fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::x inline constexpr
Returns the state estimate vector X.
Returns
The state estimate vector X.
Complexity
Constant.
Definition at line 918 of file kalman.hpp.
{
  return filter.x;
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::x().
Referenced by fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::x().
x() [2/5]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::x (auto && value, auto &&... values) inline constexpr
Sets the state estimate vector X.
Parameters
value The first moved initializer used to set the state estimate vector X.
values The second and other moved initializers to set the state estimate vector X.
Complexity
Constant.
Todo:
Consider if a fluent interface would be preferrable? In addition to constructors? Same question for all characteristics set methods.
Definition at line 958 of file kalman.hpp.
{
  filter.x = std::move(state{ std::forward<decltype(value)>(value),
                              std::forward<decltype(values)>(values)... });
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::x().
x() [3/5]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::x (const auto & value, const auto &... values) inline constexpr
Sets the state estimate vector X.
Parameters
value The first copied initializer used to set the state estimate vector X.
values The second and other copied initializers to set the state estimate vector X.
Complexity
Constant.
Todo:
Consider if a fluent interface would be preferrable? In addition to constructors? Same question for all characteristics set methods.
Definition at line 948 of file kalman.hpp.
{
  filter.x = std::move(state{ value, values... });
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::x().
x() [4/5]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::x (const state & value) inline constexpr
Sets the state estimate vector X.
Parameters
value The copied state estimate vector X.
Complexity
Constant.
Definition at line 928 of file kalman.hpp.
{
  filter.x = value;
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::x().
x() [5/5]
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::x (state && value) inline constexpr
Sets the state estimate vector X.
Parameters
value The moved state estimate vector X.
Complexity
Constant.
Definition at line 938 of file kalman.hpp.
{
  filter.x = std::move(value);
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::x().
y()
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr auto fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::y inline constexpr
Returns the innovation vector Y.
Returns
The innovation vector Y.
Complexity
Constant.
Definition at line 1305 of file kalman.hpp.
{
  return filter.y;
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::y().
Referenced by fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::y().
z()
template<typename Type , typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr auto fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::z inline constexpr
Returns the observation vector Z.
Returns
The observation vector Z.
Complexity
Constant.
Definition at line 969 of file kalman.hpp.
{
  return filter.z;
}
References fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::z().
Referenced by fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::z().
Member Data Documentation
filter
template<typename Type = double, typename State = Type, typename Output = State, typename Input = State, typename Transpose = std::identity, typename Symmetrize = std::identity, typename Divide = std::divides<void>, typename Identity = internal::identity, typename... PredictionArguments> implementation fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::filter private
Encapsulates the implementation details of the filter.
Definition at line 908 of file kalman.hpp.
Referenced by fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::f(), fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::g(), fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::h(), fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::observation(), fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::operator()(), fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::q(), fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::r(), and fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::transition().
The documentation for this class was generated from the following file:
include/fcarouge/kalman.hpp