Kalman: fcarouge Namespace Reference
fcarouge Namespace Reference
Francois Carouge's projects namespace.
Namespaces
namespace benchmark
Benchmark implementation.
namespace internal
Internal implementation details.
namespace sample
Examples, tutorials, demonstrators of the library.
namespace test
Unit, integration, regression, and usage tests.
Classes
class kalman
struct matrix
Coroutine lazy matrix.
Concepts
concept arithmetic
Arithmetic concept.
concept algebraic
Algebraic concept.
concept eigen
Eigen3 algebraic concept.
concept has_input
Filter input support concept.
concept has_process_uncertainty
Filter process uncertainty support concept.
concept has_output_uncertainty
Filter output uncertainty support concept.
concept has_input_control
Filter input control support concept.
concept has_state_transition
Filter state transition support concept.
concept has_output_model
Filter output model support concept.
Typedefs
Algebraic Types
Naive matrix.
An array-of-arrays naive implementation matrix. The implementation is constexpr compatible.
Template Parameters
Type The matrix element type.
Row The number of rows of the matrix.
Column The number of columns of the matrix.
template<typename Type = double, auto Row = 1, auto Column = 1>
using matrix = Eigen::Matrix< Type, Row, Column >
Compile-time sized Eigen3 matrix.
template<typename Type = double, auto Column = 1>
using row_vector = Eigen::RowVector< Type, Column >
Compile-time sized Eigen3 row vector.
template<typename Type = double, auto Row = 1>
using column_vector = Eigen::Vector< Type, Row >
Compile-time sized Eigen3 column vector.
Functions
template<std::ranges::range Range>
constexpr std::generator< typename Range::value_type > make_generator (Range elements)
template<typename Type >
constexpr auto make_generator (Type element) -> std::generator< Type >
template<std::invocable L>
bool operator== (L lhs, L rhs)
template<std::invocable L, typename T >
bool operator== (L lhs, T rhs)
template<typename Type , auto Row, auto Column, bool CopyableOrNot1, bool CopyableOrNot2>
constexpr bool operator== (matrix< Type, Row, Column, CopyableOrNot1 > lhs, matrix< Type, Row, Column, CopyableOrNot2 > rhs)
template<typename Type , auto Row, auto Size>
matrix< Type, Row, 1 > operator* (matrix< Type, Row, Size > lhs, matrix< Type, Size, 1 > rhs)
template<typename Type , auto Row, auto Column>
matrix< Type, Row, Column > operator* (matrix< Type, Row, Column > lhs, arithmetic auto rhs)
template<typename Type >
matrix< Type, 1, 1 > operator+ (Type lhs, matrix< Type, 1, 1 > rhs)
template<typename Type , auto Row, auto Column>
matrix< Type, Row, Column > operator+ (matrix< Type, Row, Column > lhs, matrix< Type, Row, Column > rhs)
template<typename Type , auto Row, auto Column>
constexpr bool operator== (const matrix< Type, Row, Column > &lhs, const matrix< Type, Row, Column > &rhs)
template<typename Type , auto Row, auto Column, auto Size>
constexpr auto operator* (const matrix< Type, Row, Size > &lhs, const matrix< Type, Size, Column > &rhs)
template<typename Type >
constexpr auto operator* (arithmetic auto lhs, const matrix< Type, 1, 1 > rhs)
template<typename Type , auto Column>
constexpr auto operator* (arithmetic auto lhs, matrix< Type, 1, Column > rhs)
template<typename Type , auto Row, auto Column>
constexpr auto & operator*= (matrix< Type, Row, Column > &lhs, arithmetic auto rhs)
template<typename Type , auto Row, auto Column>
constexpr auto operator* (matrix< Type, Row, Column > lhs, arithmetic auto rhs)
template<typename Type , auto Row, auto Column>
constexpr auto operator+ (const matrix< Type, Row, Column > &lhs, const matrix< Type, Row, Column > &rhs)
template<typename Type >
constexpr auto operator+ (arithmetic auto lhs, matrix< Type, 1, 1 > rhs)
template<typename Type >
constexpr auto operator+ (matrix< Type, 1, 1 > lhs, arithmetic auto rhs)
template<typename Type , auto Row, auto Column>
constexpr auto operator- (const matrix< Type, Row, Column > &lhs, const matrix< Type, Row, Column > &rhs)
template<typename Type >
constexpr auto operator- (arithmetic auto lhs, const matrix< Type, 1, 1 > &rhs)
template<typename Type , auto Row>
constexpr auto operator/ (const matrix< Type, Row, 1 > &lhs, arithmetic auto rhs)
template<typename Type , auto Row, auto Column>
constexpr auto transpose (const matrix< Type, Row, Column > &lhs)
Deduction Guides
Deduces the filter type from its declared configuration.
The configuration arguments passed are used to determine at compile time the type of fiter to use. The objecive is to select the most performant filter within the defined configuraton parameters.
Template Parameters
Arguments The declarations of the filter configuration.
Todo:
Should the parameter be named configurations?
Should the configuration examples, supports be documented here?
template<typename... Arguments>
kalman (Arguments... arguments) -> kalman< internal::filter_t< Arguments... > >
template<typename Type >
matrix (Type) -> matrix< Type, 1, 1 >
template<typename Type , auto Row, auto Column>
matrix (const Type(&)[Row][Column]) -> matrix< Type, Row, Column >
template<typename Type , auto Row>
matrix (const Type(&)[Row]) -> matrix< Type, Row, 1 >
template<typename... Types, auto... Columns>
requires (std::conjunction_v<std::is_same<first_t<Types...>, Types>...> && ((Columns == first_v<Columns>) && ... && true))
matrix (const Types(&...rows)[Columns]) -> matrix< std::remove_cvref_t< first_t< Types... > >, sizeof...(Columns),(Columns,...)>
Functions
template<typename Numerator , algebraic Denominator>
constexpr auto operator/ (const Numerator &lhs, const Denominator &rhs) -> quotient< Numerator, Denominator >
A user-definable algebraic division solution.
Variables
template<typename Type , auto Row, auto Column>
auto make_identity_generator
template<typename Type , auto Row, auto Column>
auto make_zero_generator
Algebraic Named Values
The identity matrix naive specialization.
template<typename Type = double>
constexpr Type identity_v
The identity matrix.
template<arithmetic Arithmetic>
constexpr Arithmetic identity_v< Arithmetic > {1}
The singleton identity matrix specialization.
template<typename Type = double>
constexpr Type zero_v
The zero matrix.
template<arithmetic Arithmetic>
constexpr Arithmetic zero_v< Arithmetic > {0}
The singleton zero matrix specialization.
template<eigen Matrix>
const auto identity_v< Matrix > {Matrix::Identity()}
The identity matrix Eigen specialization.
template<eigen Matrix>
const auto zero_v< Matrix > {Matrix::Zero()}
The zero matrix Eigen specialization.
template<typename Type , auto Row, auto Column>
auto identity_v< matrix< Type, Row, Column > >
The identity matrix lazy specialization.
template<typename Type , auto Row, auto Column>
auto zero_v< matrix< Type, Row, Column > >
The zero matrix lazy specialization.
Types
A generic Kalman filter.
The Kalman filter is a Bayesian filter that uses multivariate Gaussians, a recursive state estimator, a linear quadratic estimator (LQE), and an Infinite Impulse Response (IIR) filter. It is a control theory tool applicable to signal estimation, sensor fusion, or data assimilation problems. The filter is applicable for unimodal and uncorrelated uncertainties. The filter assumes white noise, propagation and measurement functions are differentiable, and that the uncertainty stays centered on the state estimate. The filter is the optimal linear filter under assumptions. The filter updates estimates by multiplying Gaussians and predicts estimates by adding Gaussians. Designing a filter is as much art as science. Design the state $X$, $P$, the process $F$, $Q$, the measurement $Z$, $R$, the measurement function $H$, and if the system has control inputs $U$, $G$.
This library supports various simple and extended filters. The implementation is independent from linear algebra backends. Arbitrary parameters can be added to the prediction and update stages to participate in gain-scheduling or linear parameter varying (LPV) systems. The default filter type is a generalized, customizable, and extended filter. The default type parameters implement a one-state, one-output, and double-precision floating-point type filter. The default update equation uses the Joseph form. Examples illustrate various usages and implementation tradeoffs. A standard formatter specialization is included for representation of the filter states. Filters with state x output x input dimensions as 1x1x1 and 1x1x0 (no input) are supported through vanilla C++. Higher dimension filters require a linear algebra backend. Customization points and type injections allow for implementation tradeoffs.
Template Parameters
Filter Exposition only. The deduced internal filter template parameter. Class template argument deduction (CTAD) figures out the filter type based on the declared configuration. See deduction guide.
Todo:
Make this class usable in constant expressions.
Is this filter restricted to Newton's equations of motion? That is only a discretized continuous-time kinematic filter? How about non-Newtonian systems?
Symmetrization support might be superfluous. How to confirm it is safe to remove? Optional?
Would we want to support smoothers?
Prepare support for larger dataset recording for graphing, metrics of large test data to facilitate tuning.
Support filter generator from equation? Third party integration?
Compare performance of general filter with its equivalent generated?
Support ranges operator filter?
Support mux pipes https://github.com/joboccara/pipes operator filter?
Reproduce Ardupilot's inertial navigation EKF and comparison benchmarks in SITL (software in the loop simulation).
Should we provide the operator[] for the vector characteristics regardless of implementation? And for the matrix ones too? It could simplify client code.
Should we provide the operator[] for state directly on the filter? Is the state X always what the user would want?
Should a fluent interface be useful in addition to the imperative and declarative paradigms support?
Expand std::format support with standard arguments and Eigen3 types?
Support, test complex number filters?
Use automatic (Eigen::AutoDiffScalar?), symbolic, numerical solvers to define the filter characteristics and simplify solving the dynamic system for non-mathematicians.
Support, use "Taking Static Type-Safety to the Next Level - Physical Units for Matrices" by Daniel Withopf and record the lesson learned: both usage and development is harder without compile time units verification.
Should we add back the call operator? How to resolve the update/predict ordering? And parameter ordering?
Should we support the noise cross covariance N = E[wv] for correlated noise sources, with default to null?
Can we implement Temporal Parallelization of Bayesian Smoothers, Simo Sarkka, Senior Member, IEEE, Angel F. Garc a-Fernandez, https://arxiv.org/pdf/1905.13002.pdf ? GPU implementation? Parallel implementation?
template<typename... Types>
using pack = internal::pack< Types... >
Tuple-like pack type.
using empty_pack = internal::empty_pack
Tuple-like empty pack type.
template<typename... Types>
using first_t = internal::first_t< Types... >
Unpack the first type of the type template parameter pack.
template<typename Numerator , typename Denominator >
using quotient = internal::quotient< Numerator, Denominator >
The matrix type satisfying X * Row = Column.
template<auto... Values>
constexpr auto first_v {internal::first_v<Values...>}
Unpack the first value of the non-type template parameter pack.
Detailed Description
Francois Carouge's projects namespace.
The definitions and implementations of the library intended for public usage. Lowers the name conflict probability in large projects. Use using-declarations or namespace-alias-definition per your project guidelines.
Todo:
Remove the dependency on std::initializer_list if possible?
Typedef Documentation
column_vector
template<typename Type = double, auto Row = 1> using fcarouge::column_vector = typedef matrix<Type, Row, decltype(Row){1}>
Compile-time sized Eigen3 column vector.
Column vector.
Coroutine lazy column vector.
Examples
ekf_4x1x0_soaring.cpp, kf_1x1x0_building_height.cpp, kf_1x1x0_liquid_temperature.cpp, kf_1x1x1_dog_position.cpp, kf_2x1x1_rocket_altitude.cpp, kf_6x2x0_vehicle_location.cpp, and kf_8x4x0_deep_sort_bounding_box.cpp.
Definition at line 73 of file linalg.hpp.
empty_pack
using fcarouge::empty_pack = typedef internal::empty_pack
Tuple-like empty pack type.
A pack type with no composed types.
Definition at line 128 of file utility.hpp.
first_t
template<typename... Types> using fcarouge::first_t = typedef internal::first_t<Types...>
Unpack the first type of the type template parameter pack.
Definition at line 131 of file utility.hpp.
matrix
template<typename Type = double, auto Row = 1, auto Column = 1> using fcarouge::matrix = typedef Eigen::Matrix<Type, Row, Column>
Compile-time sized Eigen3 matrix.
Facade for Eigen3 implementation compatibility.
Template Parameters
Type The matrix element type.
Row The number of rows of the matrix.
Column The number of columns of the matrix.
Definition at line 65 of file linalg.hpp.
pack
template<typename... Types> using fcarouge::pack = typedef internal::pack<Types...>
Tuple-like pack type.
An alternative to tuple-like types.
Definition at line 123 of file utility.hpp.
quotient
template<typename Numerator , typename Denominator > using fcarouge::quotient = typedef internal::quotient<Numerator, Denominator>
The matrix type satisfying X * Row = Column.
The resulting type of a matrix division. The resulting matrix type has as many rows as the Row matrix, respectively for columns as the Column matrix.
Definition at line 143 of file utility.hpp.
row_vector
template<typename Type = double, auto Column = 1> using fcarouge::row_vector = typedef matrix<Type, decltype(Column){1}, Column>
Compile-time sized Eigen3 row vector.
Row vector.
Coroutine lazy row vector.
Definition at line 69 of file linalg.hpp.
Function Documentation
kalman()
template<typename... Arguments> fcarouge::kalman (Arguments... arguments) -> kalman< internal::filter_t< Arguments... > >
make_generator() [1/2]
template<std::ranges::range Range> constexpr std::generator< typename Range::value_type > fcarouge::make_generator (Range elements) inline constexpr
Definition at line 67 of file linalg.hpp.
{
  return [](auto elements_copy)
             -> std::generator<typename decltype(elements)::value_type> {
    for (auto &&element : elements_copy) { // std::ranges::elements_of
      co_yield element;
    }
  }(elements);
}
Referenced by fcarouge::matrix< Type, Row, Column, Copyable >::clone(), fcarouge::matrix< Type, Row, Column, Copyable >::explicit(), fcarouge::matrix< Type, Row, Column, Copyable >::operator()(), fcarouge::matrix< Type, Row, Column, Copyable >::operator()(), operator==(), and fcarouge::matrix< Type, Row, Column, Copyable >::operator[]().
make_generator() [2/2]
template<typename Type > constexpr auto fcarouge::make_generator (Type element) -> std::generator<Type> inline constexpr
Definition at line 78 of file linalg.hpp.
{
  return [](Type element_copy) -> std::generator<Type> {
    co_yield element_copy;
  }(element);
}
matrix() [1/4]
template<typename Type , auto Row> fcarouge::matrix (const Type(&)[Row]) -> matrix< Type, Row, 1 >
matrix() [2/4]
template<typename Type , auto Row, auto Column> fcarouge::matrix (const Type(&)[Row][Column]) -> matrix< Type, Row, Column >
matrix() [3/4]
template<typename... Types, auto... Columns> requires (std::conjunction_v<std::is_same<first_t<Types...>, Types>...> && ((Columns == first_v<Columns>) && ... && true)) fcarouge::matrix (const Types(&...rows)[Columns]) -> matrix< std::remove_cvref_t< first_t< Types... > >, sizeof...(Columns),(Columns,...)>
matrix() [4/4]
template<typename Type > fcarouge::matrix (Type) -> matrix< Type, 1, 1 >
operator*() [1/6]
template<typename Type > constexpr auto fcarouge::operator* (arithmetic auto lhs, const matrix< Type, 1, 1 > rhs) inline constexpr
Definition at line 249 of file linalg.hpp.
{
  return lhs * rhs.data[0][0];
}
operator*() [2/6]
template<typename Type , auto Column> constexpr auto fcarouge::operator* (arithmetic auto lhs, matrix< Type, 1, Column > rhs) inline constexpr
Definition at line 255 of file linalg.hpp.
{
  matrix<Type, 1, Column> result;
  for (decltype(Column) j{0}; j < Column; ++j) {
    result.data[0][j] = lhs * rhs.data[0][j];
  }
  return result;
}
operator*() [3/6]
template<typename Type , auto Row, auto Column, auto Size> constexpr auto fcarouge::operator* (const matrix< Type, Row, Size > & lhs, const matrix< Type, Size, Column > & rhs) inline constexpr
Definition at line 233 of file linalg.hpp.
{
  matrix<Type, Row, Column> result;
  for (decltype(Row) i{0}; i < Row; ++i) {
    for (decltype(Column) j{0}; j < Column; ++j) {
      for (decltype(Size) k{0}; k < Size; ++k) {
        result.data[i][j] += lhs.data[i][k] * rhs.data[k][j];
      }
    }
  }
  return result;
}
operator*() [4/6]
template<typename Type , auto Row, auto Column> matrix< Type, Row, Column > fcarouge::operator* (matrix< Type, Row, Column > lhs, arithmetic auto rhs) inline
Definition at line 394 of file linalg.hpp.
{
  auto next{lhs.begin()};
  for (auto k{Row * Column}; k > 0; --k, ++next) {
    co_yield *next *rhs;
  }
}
References operator*().
operator*() [5/6]
template<typename Type , auto Row, auto Column> constexpr auto fcarouge::operator* (matrix< Type, Row, Column > lhs, arithmetic auto rhs) inline constexpr
Definition at line 279 of file linalg.hpp.
{
  return lhs *= rhs;
}
operator*() [6/6]
template<typename Type , auto Row, auto Size> matrix< Type, Row, 1 > fcarouge::operator* (matrix< Type, Row, Size > lhs, matrix< Type, Size, 1 > rhs) inline
Definition at line 377 of file linalg.hpp.
{
  // fix me?
  auto next1{lhs.begin()};
  for (decltype(Row) i{0}; i < Row; ++i) {       // chunk_by_rows
    matrix<Type, Size, 1> rhs_copy{rhs.clone()}; // repeat_n
    auto next2{rhs_copy.begin()};
    Type element{}; // inner_product?
    for (decltype(Size) k{0}; k < Size; ++k, ++next1, ++next2) {
      element += *next1 * *next2;
    }
    co_yield element;
  }
}
References operator*().
Referenced by operator*(), and operator*().
operator*=()
template<typename Type , auto Row, auto Column> constexpr auto & fcarouge::operator*= (matrix< Type, Row, Column > & lhs, arithmetic auto rhs) inline constexpr
Definition at line 267 of file linalg.hpp.
{
  for (decltype(Row) i{0}; i < Row; ++i) {
    for (decltype(Column) j{0}; j < Column; ++j) {
      lhs.data[i][j] *= rhs;
    }
  }
  return lhs;
}
operator+() [1/5]
template<typename Type > constexpr auto fcarouge::operator+ (arithmetic auto lhs, matrix< Type, 1, 1 > rhs) inline constexpr
Definition at line 300 of file linalg.hpp.
{
  return lhs + rhs.data[0][0];
}
operator+() [2/5]
template<typename Type , auto Row, auto Column> constexpr auto fcarouge::operator+ (const matrix< Type, Row, Column > & lhs, const matrix< Type, Row, Column > & rhs) inline constexpr
Definition at line 286 of file linalg.hpp.
{
  matrix<Type, Row, Column> result{lhs};
  for (decltype(Row) i{0}; i < Row; ++i) {
    for (decltype(Column) j{0}; j < Column; ++j) {
      result.data[i][j] += rhs.data[i][j];
    }
  }
  return result;
}
operator+() [3/5]
template<typename Type > constexpr auto fcarouge::operator+ (matrix< Type, 1, 1 > lhs, arithmetic auto rhs) inline constexpr
Definition at line 306 of file linalg.hpp.
{
  return lhs.data[0][0] + rhs;
}
operator+() [4/5]
template<typename Type , auto Row, auto Column> matrix< Type, Row, Column > fcarouge::operator+ (matrix< Type, Row, Column > lhs, matrix< Type, Row, Column > rhs) inline
Definition at line 409 of file linalg.hpp.
{
  auto next1{lhs.begin()};
  auto next2{rhs.begin()};
  for (auto k{Row * Column}; k > 0; --k, ++next1, ++next2) {
    co_yield *next1 + *next2;
  }
}
References operator+().
operator+() [5/5]
template<typename Type > matrix< Type, 1, 1 > fcarouge::operator+ (Type lhs, matrix< Type, 1, 1 > rhs) inline
Definition at line 402 of file linalg.hpp.
{
  co_yield lhs + *rhs.begin();
}
References operator+().
Referenced by operator+(), and operator+().
operator-() [1/2]
template<typename Type > constexpr auto fcarouge::operator- (arithmetic auto lhs, const matrix< Type, 1, 1 > & rhs) inline constexpr
Definition at line 327 of file linalg.hpp.
{
  return lhs - rhs.data[0][0];
}
operator-() [2/2]
template<typename Type , auto Row, auto Column> constexpr auto fcarouge::operator- (const matrix< Type, Row, Column > & lhs, const matrix< Type, Row, Column > & rhs) inline constexpr
Definition at line 313 of file linalg.hpp.
{
  matrix<Type, Row, Column> result{lhs};
  for (decltype(Row) i{0}; i < Row; ++i) {
    for (decltype(Column) j{0}; j < Column; ++j) {
      result.data[i][j] -= rhs.data[i][j];
    }
  }
  return result;
}
operator/() [1/2]
template<typename Type , auto Row> constexpr auto fcarouge::operator/ (const matrix< Type, Row, 1 > & lhs, arithmetic auto rhs) inline constexpr
Definition at line 333 of file linalg.hpp.
{
  matrix<Type, Row, 1> result{lhs};
  for (decltype(Row) i{0}; i < Row; ++i) {
    result.data[i][0] /= rhs;
  }
  return result;
}
operator/() [2/2]
template<typename Numerator , algebraic Denominator> constexpr auto fcarouge::operator/ (const Numerator & lhs, const Denominator & rhs) -> quotient<Numerator, Denominator> constexpr
A user-definable algebraic division solution.
Implemented for known libraries. User-definable in other cases. There exists several ways to find X in X = lhs * rhs^-1 for different tradeoffs. The user provides their implementation. Often, matrix inversion is avoided by solving X * rhs = lhs for rhs through a decomposer.
Examples
kf_6x2x0_vehicle_location.cpp, and kf_8x4x0_deep_sort_bounding_box.cpp.
Definition at line 55 of file update_linalg_xx0.cpp.
{
  return rhs.transpose()
      .fullPivHouseholderQr()
      .solve(lhs.transpose())
      .transpose();
}
operator==() [1/4]
template<typename Type , auto Row, auto Column> constexpr bool fcarouge::operator== (const matrix< Type, Row, Column > & lhs, const matrix< Type, Row, Column > & rhs) inline constexpr
Definition at line 219 of file linalg.hpp.
{
  for (decltype(Row) i{0}; i < Row; ++i) {
    for (decltype(Column) j{0}; j < Column; ++j) {
      if (lhs.data[i][j] != rhs.data[i][j]) {
        return false;
      }
    }
  }
  return true;
}
operator==() [2/4]
template<std::invocable L> bool fcarouge::operator== (L lhs, L rhs)
Definition at line 352 of file linalg.hpp.
{
  return lhs() == rhs();
}
References operator==().
Referenced by operator==(), operator==(), and operator==().
operator==() [3/4]
template<std::invocable L, typename T > bool fcarouge::operator== (L lhs, T rhs)
Definition at line 356 of file linalg.hpp.
{
  return lhs() == rhs;
}
References operator==().
operator==() [4/4]
template<typename Type , auto Row, auto Column, bool CopyableOrNot1, bool CopyableOrNot2> constexpr bool fcarouge::operator== (matrix< Type, Row, Column, CopyableOrNot1 > lhs, matrix< Type, Row, Column, CopyableOrNot2 > rhs) inline constexpr
Definition at line 363 of file linalg.hpp.
{
  std::array<Type, Row * Column> lhs_elements; // std::ranges::to
  std::ranges::copy(lhs.genie, lhs_elements.begin());
  lhs.genie = make_generator(lhs_elements);
  std::array<Type, Row * Column> rhs_elements; // std::ranges::to
  std::ranges::copy(rhs.genie, rhs_elements.begin());
  rhs.genie = make_generator(rhs_elements);
  return lhs_elements == rhs_elements;
}
References make_generator(), and operator==().
transpose()
template<typename Type , auto Row, auto Column> constexpr auto fcarouge::transpose (const matrix< Type, Row, Column > & lhs) inline constexpr
Definition at line 346 of file linalg.hpp.
{
  matrix<Type, Column, Row> result;
  for (decltype(Row) i{0}; i < Row; ++i) {
    for (decltype(Column) j{0}; j < Column; ++j) {
      result.data[j][i] = lhs.data[i][j];
    }
  }
  return result;
}
Variable Documentation
first_v
template<auto... Values> constexpr auto fcarouge::first_v {internal::first_v<Values...>} inline constexpr
Unpack the first value of the non-type template parameter pack.
Definition at line 135 of file utility.hpp.
{internal::first_v<Values...>};
identity_v
template<typename Type = double> constexpr Type fcarouge::identity_v inline constexpr
Initial value:
{internal::not_implemented<Type>{
    "Implement the linear algebra identity matrix for this type."}}
The identity matrix.
User-defined.
Definition at line 167 of file utility.hpp.
                                {internal::not_implemented<Type>{
    "Implement the linear algebra identity matrix for this type."}};
identity_v< Arithmetic >
template<arithmetic Arithmetic> constexpr Arithmetic fcarouge::identity_v< Arithmetic > {1} inline constexpr
The singleton identity matrix specialization.
Definition at line 172 of file utility.hpp.
{1};
identity_v< Matrix >
template<eigen Matrix> const auto fcarouge::identity_v< Matrix > {Matrix::Identity()} inline
The identity matrix Eigen specialization.
Definition at line 81 of file linalg.hpp.
{Matrix::Identity()};
identity_v< matrix< Type, Row, Column > >
template<typename Type , auto Row, auto Column> constexpr matrix<Type, Row, Column> fcarouge::identity_v< matrix< Type, Row, Column > > inline constexpr
Initial value:
{[](auto... args) {
  matrix<Type, Row, Column, true> m{
      make_identity_generator<Type, Row, Column>()};
  if constexpr (sizeof...(args)) {
    return m(args...);
  } else {
    return m;
  }
}}
The identity matrix lazy specialization.
Definition at line 329 of file linalg.hpp.
                                          {[](auto... args) {
  matrix<Type, Row, Column, true> m{
      make_identity_generator<Type, Row, Column>()};
  if constexpr (sizeof...(args)) {
    return m(args...);
  } else {
    return m;
  }
}};
make_identity_generator
template<typename Type , auto Row, auto Column> auto fcarouge::make_identity_generator
Initial value:
{[]() -> std::generator<Type> {
  for (decltype(Row) i{0}; i < Row; ++i) {
    for (decltype(Column) j{0}; j < Column; ++j) {
      co_yield i == j;
    }
  }
}}
Definition at line 309 of file linalg.hpp.
                            {[]() -> std::generator<Type> {
  for (decltype(Row) i{0}; i < Row; ++i) {
    for (decltype(Column) j{0}; j < Column; ++j) {
      co_yield i == j;
    }
  }
}};
make_zero_generator
template<typename Type , auto Row, auto Column> auto fcarouge::make_zero_generator
Initial value:
{[]() -> std::generator<Type> {
  for (auto k{Row * Column}; k > 0; --k) {
    co_yield 0.0;
  }
}}
Definition at line 318 of file linalg.hpp.
                        {[]() -> std::generator<Type> {
  for (auto k{Row * Column}; k > 0; --k) {
    co_yield 0.0;
  }
}};
zero_v
template<typename Type = double> constexpr Type fcarouge::zero_v inline constexpr
Initial value:
{internal::not_implemented<Type>{
    "Implement the linear algebra zero matrix for this type."}}
The zero matrix.
User-defined.
Definition at line 178 of file utility.hpp.
                            {internal::not_implemented<Type>{
    "Implement the linear algebra zero matrix for this type."}};
zero_v< Arithmetic >
template<arithmetic Arithmetic> constexpr Arithmetic fcarouge::zero_v< Arithmetic > {0} inline constexpr
The singleton zero matrix specialization.
Definition at line 183 of file utility.hpp.
{0};
zero_v< Matrix >
template<eigen Matrix> const auto fcarouge::zero_v< Matrix > {Matrix::Zero()} inline
The zero matrix Eigen specialization.
Definition at line 84 of file linalg.hpp.
{Matrix::Zero()};
zero_v< matrix< Type, Row, Column > >
template<typename Type , auto Row, auto Column> constexpr matrix<Type, Row, Column> fcarouge::zero_v< matrix< Type, Row, Column > > inline constexpr
Initial value:
{[](auto... args) {
  matrix<Type, Row, Column, true> m{make_zero_generator<Type, Row, Column>()};
  if constexpr (sizeof...(args)) {
    return m(args...);
  } else {
    return m;
  }
}}
The zero matrix lazy specialization.
The zero matrix naive specialization.
Definition at line 341 of file linalg.hpp.
                                      {[](auto... args) {
  matrix<Type, Row, Column, true> m{make_zero_generator<Type, Row, Column>()};
  if constexpr (sizeof...(args)) {
    return m(args...);
  } else {
    return m;
  }
}};