Kalman: fcarouge::naive Namespace Reference
fcarouge::naive Namespace Reference
Classes
struct matrix
Naive matrix.
Typedefs
Types
template<typename Type = double, std::size_t Column = 1>
using row_vector = matrix<Type, decltype(Column){1}, Column>
Row vector.
template<typename Type = double, std::size_t Row = 1>
using column_vector = matrix<Type, Row, decltype(Row){1}>
Column vector.
Functions
template<typename Type , std::size_t Row, std::size_t Column>
constexpr bool operator== (const matrix< Type, Row, Column > &lhs, const matrix< Type, Row, Column > &rhs)
template<typename Type , std::size_t Row, std::size_t Column, std::size_t Size>
constexpr auto operator* (const matrix< Type, Row, Size > &lhs, const matrix< Type, Size, Column > &rhs)
template<typename Type >
constexpr auto operator* (arithmetic auto lhs, const matrix< Type, 1, 1 > rhs)
template<typename Type , std::size_t Column>
constexpr auto operator* (arithmetic auto lhs, matrix< Type, 1, Column > rhs)
template<typename Type , std::size_t Row, std::size_t Column>
constexpr auto & operator*= (matrix< Type, Row, Column > &lhs, arithmetic auto rhs)
template<typename Type , std::size_t Row, std::size_t Column>
constexpr auto operator* (matrix< Type, Row, Column > lhs, arithmetic auto rhs)
template<typename Type , std::size_t Row, std::size_t Column>
constexpr auto operator+ (const matrix< Type, Row, Column > &lhs, const matrix< Type, Row, Column > &rhs)
template<typename Type >
constexpr auto operator+ (arithmetic auto lhs, matrix< Type, 1, 1 > rhs)
template<typename Type >
constexpr auto operator+ (matrix< Type, 1, 1 > lhs, arithmetic auto rhs)
template<typename Type , std::size_t Row, std::size_t Column>
constexpr auto operator- (const matrix< Type, Row, Column > &lhs, const matrix< Type, Row, Column > &rhs)
template<typename Type >
constexpr auto operator- (arithmetic auto lhs, const matrix< Type, 1, 1 > &rhs)
template<typename Type , std::size_t Row>
constexpr auto operator/ (const matrix< Type, Row, 1 > &lhs, arithmetic auto rhs)
Deduction Guides
template<typename Type >
matrix (Type) -> matrix< Type, 1, 1 >
template<typename Type , std::size_t Row, std::size_t Column>
matrix (const Type(&)[Row][Column]) -> matrix< Type, Row, Column >
template<typename Type , std::size_t Row>
matrix (const Type(&)[Row]) -> matrix< Type, Row, 1 >
template<typename... Types, std::size_t... Columns>
requires (std::conjunction_v<std::is_same<first<Types...>, Types>...> && ((Columns == first_v<Columns>) && ... && true))
matrix (const Types(&...rows)[Columns]) -> matrix< std::remove_cvref_t< first< Types... > >, sizeof...(Columns),(Columns,...)>
Typedef Documentation
column_vector
template<typename Type = double, std::size_t Row = 1> using fcarouge::naive::column_vector = matrix<Type, Row, decltype(Row){1}>
Column vector.
Definition at line 215 of file naive.hpp.
{1}>;
row_vector
template<typename Type = double, std::size_t Column = 1> using fcarouge::naive::row_vector = matrix<Type, decltype(Column){1}, Column>
Row vector.
Definition at line 211 of file naive.hpp.
{1}, Column>;
Function Documentation
matrix() [1/4]
template<typename Type , std::size_t Row> fcarouge::naive::matrix (const Type(&)[Row]) -> matrix< Type, Row, 1 >
matrix() [2/4]
template<typename Type , std::size_t Row, std::size_t Column> fcarouge::naive::matrix (const Type(&)[Row][Column]) -> matrix< Type, Row, Column >
matrix() [3/4]
template<typename... Types, std::size_t... Columns> requires (std::conjunction_v<std::is_same<first<Types...>, Types>...> && ((Columns == first_v<Columns>) && ... && true)) fcarouge::naive::matrix (const Types(&...rows)[Columns]) -> matrix< std::remove_cvref_t< first< Types... > >, sizeof...(Columns),(Columns,...)>
matrix() [4/4]
template<typename Type > fcarouge::naive::matrix (Type) -> matrix< Type, 1, 1 >
operator*() [1/4]
template<typename Type > auto fcarouge::naive::operator* (arithmetic auto lhs, const matrix< Type, 1, 1 > rhs) inline nodiscard constexpr
Definition at line 272 of file naive.hpp.
{
  return lhs * rhs.data[0][0];
}
References fcarouge::naive::matrix< Type, Row, Column >::data, and fcarouge::operator*().
operator*() [2/4]
template<typename Type , std::size_t Column> auto fcarouge::naive::operator* (arithmetic auto lhs, matrix< Type, 1, Column > rhs) inline nodiscard constexpr
Definition at line 278 of file naive.hpp.
{
  matrix<Type, 1, Column> result;
  for (decltype(Column) j{0}; j < Column; ++j) {
    result.data[0][j] = lhs * rhs.data[0][j];
  }
  return result;
}
References fcarouge::naive::matrix< Type, Row, Column >::data, and fcarouge::operator*().
operator*() [3/4]
template<typename Type , std::size_t Row, std::size_t Column, std::size_t Size> auto fcarouge::naive::operator* (const matrix< Type, Row, Size > & lhs, const matrix< Type, Size, Column > & rhs) inline nodiscard constexpr
Definition at line 256 of file naive.hpp.
{
  matrix<Type, Row, Column> result;
  for (decltype(Row) i{0}; i < Row; ++i) {
    for (decltype(Column) j{0}; j < Column; ++j) {
      for (decltype(Size) k{0}; k < Size; ++k) {
        result.data[i][j] += lhs.data[i][k] * rhs.data[k][j];
      }
    }
  }
  return result;
}
References fcarouge::naive::matrix< Type, Row, Column >::data, and fcarouge::operator*().
operator*() [4/4]
template<typename Type , std::size_t Row, std::size_t Column> auto fcarouge::naive::operator* (matrix< Type, Row, Column > lhs, arithmetic auto rhs) inline nodiscard constexpr
Definition at line 302 of file naive.hpp.
{
  return lhs *= rhs;
}
References fcarouge::operator*().
operator*=()
template<typename Type , std::size_t Row, std::size_t Column> auto & fcarouge::naive::operator*= (matrix< Type, Row, Column > & lhs, arithmetic auto rhs) inline constexpr
Definition at line 290 of file naive.hpp.
{
  for (decltype(Row) i{0}; i < Row; ++i) {
    for (decltype(Column) j{0}; j < Column; ++j) {
      lhs.data[i][j] *= rhs;
    }
  }
  return lhs;
}
References fcarouge::naive::matrix< Type, Row, Column >::data, and operator*=().
Referenced by operator*=().
operator+() [1/3]
template<typename Type > auto fcarouge::naive::operator+ (arithmetic auto lhs, matrix< Type, 1, 1 > rhs) inline nodiscard constexpr
Definition at line 323 of file naive.hpp.
{
  return lhs + rhs.data[0][0];
}
References fcarouge::naive::matrix< Type, Row, Column >::data, and fcarouge::operator+().
operator+() [2/3]
template<typename Type , std::size_t Row, std::size_t Column> auto fcarouge::naive::operator+ (const matrix< Type, Row, Column > & lhs, const matrix< Type, Row, Column > & rhs) inline nodiscard constexpr
Definition at line 309 of file naive.hpp.
{
  matrix<Type, Row, Column> result{lhs};
  for (decltype(Row) i{0}; i < Row; ++i) {
    for (decltype(Column) j{0}; j < Column; ++j) {
      result.data[i][j] += rhs.data[i][j];
    }
  }
  return result;
}
References fcarouge::naive::matrix< Type, Row, Column >::data, and fcarouge::operator+().
operator+() [3/3]
template<typename Type > auto fcarouge::naive::operator+ (matrix< Type, 1, 1 > lhs, arithmetic auto rhs) inline nodiscard constexpr
Definition at line 329 of file naive.hpp.
{
  return lhs.data[0][0] + rhs;
}
References fcarouge::naive::matrix< Type, Row, Column >::data, and fcarouge::operator+().
operator-() [1/2]
template<typename Type > auto fcarouge::naive::operator- (arithmetic auto lhs, const matrix< Type, 1, 1 > & rhs) inline nodiscard constexpr
Definition at line 350 of file naive.hpp.
{
  return lhs - rhs.data[0][0];
}
References fcarouge::naive::matrix< Type, Row, Column >::data, and operator-().
operator-() [2/2]
template<typename Type , std::size_t Row, std::size_t Column> auto fcarouge::naive::operator- (const matrix< Type, Row, Column > & lhs, const matrix< Type, Row, Column > & rhs) inline nodiscard constexpr
Definition at line 336 of file naive.hpp.
{
  matrix<Type, Row, Column> result{lhs};
  for (decltype(Row) i{0}; i < Row; ++i) {
    for (decltype(Column) j{0}; j < Column; ++j) {
      result.data[i][j] -= rhs.data[i][j];
    }
  }
  return result;
}
References fcarouge::naive::matrix< Type, Row, Column >::data, and operator-().
Referenced by operator-(), and operator-().
operator/()
template<typename Type , std::size_t Row> auto fcarouge::naive::operator/ (const matrix< Type, Row, 1 > & lhs, arithmetic auto rhs) inline nodiscard constexpr
Definition at line 356 of file naive.hpp.
{
  matrix<Type, Row, 1> result{lhs};
  for (decltype(Row) i{0}; i < Row; ++i) {
    result.data[i][0] /= rhs;
  }
  return result;
}
operator==()
template<typename Type , std::size_t Row, std::size_t Column> bool fcarouge::naive::operator== (const matrix< Type, Row, Column > & lhs, const matrix< Type, Row, Column > & rhs) inline nodiscard constexpr
Definition at line 242 of file naive.hpp.
{
  for (decltype(Row) i{0}; i < Row; ++i) {
    for (decltype(Column) j{0}; j < Column; ++j) {
      if (lhs.data[i][j] != rhs.data[i][j]) {
        return false;
      }
    }
  }
  return true;
}
References fcarouge::naive::matrix< Type, Row, Column >::data, and fcarouge::operator==().