Kalman: fcarouge::eigen::benchmark Namespace Reference
fcarouge::eigen::benchmark Namespace Reference
Typedefs
using clock = fcarouge::benchmark::clock
Type of the platform steady benchmark clock.
Functions
template<std::size_t StateSize, std::size_t InputSize>
void eigen_predict (::benchmark::State &state)
Name ("eigen_predict_${STATE_SIZE}x1x${INPUT_SIZE}") -> Unit(::benchmark::kNanosecond) ->ComputeStatistics("min", [](const auto &results) { return std::ranges::min(results);}) -> ComputeStatistics("max", [](const auto &results) { return std::ranges::max(results);}) -> UseManualTime() -> Complexity(::benchmark::oAuto) -> DisplayAggregatesOnly(true) -> Repetitions(100)
template<std::size_t StateSize, std::size_t OutputSize>
void eigen_update (::benchmark::State &state)
Name ("eigen_update_${STATE_SIZE}x${OUTPUT_SIZE}x0") -> Unit(::benchmark::kNanosecond) ->ComputeStatistics("min", [](const auto &results) { return std::ranges::min(results);}) -> ComputeStatistics("max", [](const auto &results) { return std::ranges::max(results);}) -> UseManualTime() -> Complexity(::benchmark::oAuto) -> DisplayAggregatesOnly(true) -> Repetitions(100)
Typedef Documentation
clock
using fcarouge::eigen::benchmark::clock = typedef fcarouge::benchmark::clock
Type of the platform steady benchmark clock.
Conveniently makes the clock available in the eigen namespace.
Definition at line 62 of file benchmark.hpp.
Function Documentation
eigen_predict()
template<std::size_t StateSize, std::size_t InputSize> void fcarouge::eigen::benchmark::eigen_predict (::benchmark::State & state)
Benchmark
Measure the prediction of the filter for different dimensions of states and inputs with the Eigen linear algebra backend.
Definition at line 58 of file eigen_predict_x1x.cpp.
{
  using kalman =
      kalman<vector<float, StateSize>, float, vector<float, InputSize>>;
  kalman filter;
  std::random_device random_device;
  std::mt19937 random_generator(random_device());
  std::uniform_real_distribution uniformly_distributed(0.f, 1.f);
  for (auto _ : state) {
    typename kalman::input u;
    fcarouge::internal::for_constexpr<std::size_t{0}, InputSize, 1>(
        [&u, &uniformly_distributed, &random_generator](auto position) {
          u[position] = uniformly_distributed(random_generator);
        });
    ::benchmark::ClobberMemory();
    const auto start{clock::now()};
    filter.predict(u);
    ::benchmark::ClobberMemory();
    const auto end{clock::now()};
    state.SetIterationTime(
        std::chrono::duration_cast<std::chrono::duration<double>>(end - start)
            .count());
  }
}
References fcarouge::internal::for_constexpr(), and fcarouge::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, UpdateTypes, PredictionTypes >::predict().
eigen_update()
template<std::size_t StateSize, std::size_t OutputSize> void fcarouge::eigen::benchmark::eigen_update (::benchmark::State & state)
Benchmark
Measure the update of the filter for different dimensions of states and outputs with the Eigen linear algebra backend.
Definition at line 58 of file eigen_update_xx0.cpp.
{
  using kalman = kalman<vector<float, StateSize>, vector<float, OutputSize>>;
  kalman filter;
  std::random_device random_device;
  std::mt19937 random_generator(random_device());
  std::uniform_real_distribution uniformly_distributed(0.f, 1.f);
  for (auto _ : state) {
    typename kalman::output z;
    fcarouge::internal::for_constexpr<std::size_t{0}, OutputSize, 1>(
        [&z, &uniformly_distributed, &random_generator](auto position) {
          z[position] = uniformly_distributed(random_generator);
        });
    ::benchmark::ClobberMemory();
    const auto start{clock::now()};
    filter.update(z);
    ::benchmark::ClobberMemory();
    const auto end{clock::now()};
    state.SetIterationTime(
        std::chrono::duration_cast<std::chrono::duration<double>>(end - start)
            .count());
  }
}
References fcarouge::internal::for_constexpr(), and fcarouge::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, UpdateTypes, PredictionTypes >::update().
Name() [1/2]
fcarouge::eigen::benchmark::Name ("eigen_predict_${STATE_SIZE}x1x${INPUT_SIZE}") -> Unit(::benchmark::kNanosecond) ->ComputeStatistics("min", [](const auto &results) { return std::ranges::min(results);}) -> ComputeStatistics("max", [](const auto &results) { return std::ranges::max(results);}) -> UseManualTime() -> Complexity(::benchmark::oAuto) -> DisplayAggregatesOnly(true) -> Repetitions(100)
Todo:
Find a way to remove macros or find a different benchmark library that doesn't use macros.
Name() [2/2]
fcarouge::eigen::benchmark::Name ("eigen_update_${STATE_SIZE}x${OUTPUT_SIZE}x0") -> Unit(::benchmark::kNanosecond) ->ComputeStatistics("min", [](const auto &results) { return std::ranges::min(results);}) -> ComputeStatistics("max", [](const auto &results) { return std::ranges::max(results);}) -> UseManualTime() -> Complexity(::benchmark::oAuto) -> DisplayAggregatesOnly(true) -> Repetitions(100)
Todo:
Find a way to remove macros or find a different benchmark library that doesn't use macros.