Kalman: fcarouge::internal Namespace Reference
fcarouge::internal Namespace Reference
Internal implementation details.
Classes
struct conditional_input
struct conditional_input< Filter >
struct conditional_input_control
struct conditional_input_control< Filter >
struct conditional_member_types
struct conditional_output_model
struct conditional_output_model< Filter >
struct conditional_output_uncertainty
struct conditional_output_uncertainty< Filter >
struct conditional_prediction_types
struct conditional_prediction_types< Filter >
struct conditional_process_uncertainty
struct conditional_process_uncertainty< Filter >
struct conditional_state_transition
struct conditional_state_transition< Filter >
struct conditional_update_types
struct conditional_update_types< Filter >
struct estimate_uncertainty
struct filter_deducer
struct first_value
class function
class function< Result(Arguments...)>
struct function_traits
struct function_traits< Result(Type::*)(Arguments...) const >
struct input_control
struct input_t
struct matrix_deducer
struct not_implemented
struct observation
struct output_model
struct output_t
struct output_uncertainty
struct prediction_types_t
struct process_uncertainty
struct repack
struct repack< Pack< Types... > >
struct state
struct state_transition
struct transition
struct transposer
struct update_types_t
struct x_z_p_q_r_h_f
struct x_z_p_q_r_hh_us_ps
struct x_z_p_q_r_hh_us_ps< State, Output, std::tuple< UpdateTypes... >, std::tuple< PredictionTypes... > >
struct x_z_p_qq_rr_f
struct x_z_p_r_f
struct x_z_u_p_q_r_f_g_ps
struct x_z_u_p_q_r_f_g_ps< State, Output, Input, std::tuple< UpdateTypes... >, std::tuple< PredictionTypes... > >
struct x_z_u_p_q_r_us_ps
struct x_z_u_p_q_r_us_ps< State, Output, Input, std::tuple< UpdateTypes... >, std::tuple< PredictionTypes... > >
Typedefs
template<typename... Arguments>
using deduce_filter = std::invoke_result_t< filter_deducer<>, Arguments... >
template<typename Callable >
using function_traits_t = function_traits< decltype(&Callable::operator())>::type
template<typename Lhs , typename Rhs >
using deduce_matrix = std::remove_cvref_t< std::invoke_result_t< matrix_deducer, Lhs, Rhs > >
using empty_tuple = std::tuple<>
template<typename Pack >
using repack_t = repack< Pack >::type
template<typename Pack >
using size_t = repack< Pack >::size_t
template<typename... Types>
using first_t = std::tuple_element_t< 0, std::tuple< Types... > >
Functions
template<typename Callable >
function (Callable) -> function< function_traits_t< Callable > >
template<typename Result , typename... Arguments>
function (Result(Arguments...)) -> function< Result(Arguments...)>
template<typename Type >
state (Type) -> state< Type >
template<typename... Types>
state (Types... elements) -> state< std::remove_cvref_t< first_t< Types... > >[sizeof...(Types)]>
template<typename Element >
estimate_uncertainty (Element) -> estimate_uncertainty< Element >
template<typename Element >
estimate_uncertainty (std::initializer_list< std::initializer_list< Element > >) -> estimate_uncertainty< std::initializer_list< std::initializer_list< Element > > >
template<typename Element >
output_uncertainty (Element) -> output_uncertainty< Element >
template<typename Element >
output_uncertainty (std::initializer_list< std::initializer_list< Element > >) -> output_uncertainty< std::initializer_list< std::initializer_list< Element > > >
template<typename Element >
process_uncertainty (Element) -> process_uncertainty< Element >
template<typename Element >
process_uncertainty (std::initializer_list< std::initializer_list< Element > >) -> process_uncertainty< std::initializer_list< std::initializer_list< Element > > >
template<typename Element >
output_model (Element) -> output_model< Element >
template<typename Element >
output_model (std::initializer_list< std::initializer_list< Element > >) -> output_model< std::initializer_list< std::initializer_list< Element > > >
template<typename Element >
state_transition (Element) -> state_transition< Element >
template<typename Element >
state_transition (std::initializer_list< std::initializer_list< Element > >) -> state_transition< std::initializer_list< std::initializer_list< Element > > >
template<typename Element >
input_control (Element) -> input_control< Element >
template<typename Element >
input_control (std::initializer_list< std::initializer_list< Element > >) -> input_control< std::initializer_list< std::initializer_list< Element > > >
template<typename Element >
transition (Element) -> transition< Element >
template<typename Element >
observation (Element) -> observation< Element >
template<auto Begin, decltype(Begin) End, decltype(Begin) Increment, typename Function >
constexpr void for_constexpr (Function &&function)
Variables
template<typename Filter >
constexpr filter_deducer< Filter > filter {}
template<typename Type >
input_t< Type > input {}
template<typename Type >
output_t< Type > output {}
template<typename... Types>
update_types_t< Types... > update_types {}
template<typename... Types>
prediction_types_t< Types... > prediction_types {}
template<typename Pack >
constexpr auto size {repack<Pack>::size}
template<auto... Values>
constexpr auto first_v {first_value<Values...>::value}
Detailed Description
Internal implementation details.
Solely intended for this library usage. Do not rely on these details in your projects.
Todo:
Remove the dependency on std::initializer_list if possible?
Typedef Documentation
deduce_filter
template<typename... Arguments> using fcarouge::internal::deduce_filter = typedef std::invoke_result_t<filter_deducer<>, Arguments...>
Definition at line 273 of file factory.hpp.
deduce_matrix
template<typename Lhs , typename Rhs > using fcarouge::internal::deduce_matrix = typedef std::remove_cvref_t<std::invoke_result_t<matrix_deducer, Lhs, Rhs> >
Definition at line 286 of file utility.hpp.
empty_tuple
using fcarouge::internal::empty_tuple = typedef std::tuple<>
Definition at line 289 of file utility.hpp.
first_t
template<typename... Types> using fcarouge::internal::first_t = typedef std::tuple_element_t<0, std::tuple<Types...> >
Definition at line 296 of file utility.hpp.
function_traits_t
template<typename Callable > using fcarouge::internal::function_traits_t = typedef function_traits<decltype(&Callable::operator())>::type
Definition at line 94 of file function.hpp.
repack_t
template<typename Pack > using fcarouge::internal::repack_t = typedef repack<Pack>::type
Definition at line 291 of file utility.hpp.
size_t
template<typename Pack > using fcarouge::internal::size_t = typedef repack<Pack>::size_t
Definition at line 293 of file utility.hpp.
Function Documentation
estimate_uncertainty() [1/2]
template<typename Element > fcarouge::internal::estimate_uncertainty (Element) -> estimate_uncertainty< Element >
References estimate_uncertainty().
Referenced by estimate_uncertainty(), estimate_uncertainty(), and state().
estimate_uncertainty() [2/2]
template<typename Element > fcarouge::internal::estimate_uncertainty (std::initializer_list< std::initializer_list< Element > >) -> estimate_uncertainty< std::initializer_list< std::initializer_list< Element > > >
References estimate_uncertainty(), and output_uncertainty().
for_constexpr()
template<auto Begin, decltype(Begin) End, decltype(Begin) Increment, typename Function > constexpr void fcarouge::internal::for_constexpr (Function && function) constexpr
Definition at line 300 of file utility.hpp.
{
  if constexpr (Begin < End) {
    function(std::integral_constant<decltype(Begin), Begin>());
    for_constexpr<Begin + Increment, End, Increment>(function);
  }
}
References function().
function() [1/2]
template<typename Callable > fcarouge::internal::function (Callable) -> function< function_traits_t< Callable > >
References function().
Referenced by for_constexpr(), function(), and function().
function() [2/2]
template<typename Result , typename... Arguments> fcarouge::internal::function (Result(Arguments...)) -> function< Result(Arguments...)>
References function().
input_control() [1/2]
template<typename Element > fcarouge::internal::input_control (Element) -> input_control< Element >
References input_control().
Referenced by input_control(), input_control(), and state_transition().
input_control() [2/2]
template<typename Element > fcarouge::internal::input_control (std::initializer_list< std::initializer_list< Element > >) -> input_control< std::initializer_list< std::initializer_list< Element > > >
References input_control(), and transition().
observation()
template<typename Element > fcarouge::internal::observation (Element) -> observation< Element >
References observation().
Referenced by observation(), and transition().
output_model() [1/2]
template<typename Element > fcarouge::internal::output_model (Element) -> output_model< Element >
References output_model().
Referenced by output_model(), and output_model().
output_model() [2/2]
template<typename Element > fcarouge::internal::output_model (std::initializer_list< std::initializer_list< Element > >) -> output_model< std::initializer_list< std::initializer_list< Element > > >
References output_model(), and state_transition().
output_uncertainty() [1/2]
template<typename Element > fcarouge::internal::output_uncertainty (Element) -> output_uncertainty< Element >
References output_uncertainty().
Referenced by estimate_uncertainty(), output_uncertainty(), and output_uncertainty().
output_uncertainty() [2/2]
template<typename Element > fcarouge::internal::output_uncertainty (std::initializer_list< std::initializer_list< Element > >) -> output_uncertainty< std::initializer_list< std::initializer_list< Element > > >
References output_uncertainty(), and process_uncertainty().
process_uncertainty() [1/2]
template<typename Element > fcarouge::internal::process_uncertainty (Element) -> process_uncertainty< Element >
References process_uncertainty().
Referenced by output_uncertainty(), process_uncertainty(), and process_uncertainty().
process_uncertainty() [2/2]
template<typename Element > fcarouge::internal::process_uncertainty (std::initializer_list< std::initializer_list< Element > >) -> process_uncertainty< std::initializer_list< std::initializer_list< Element > > >
References process_uncertainty().
state() [1/2]
template<typename Type > fcarouge::internal::state (Type) -> state< Type >
state() [2/2]
template<typename... Types> fcarouge::internal::state (Types... elements) -> state< std::remove_cvref_t< first_t< Types... > >[sizeof...(Types)]>
References estimate_uncertainty().
state_transition() [1/2]
template<typename Element > fcarouge::internal::state_transition (Element) -> state_transition< Element >
References state_transition().
Referenced by output_model(), state_transition(), and state_transition().
state_transition() [2/2]
template<typename Element > fcarouge::internal::state_transition (std::initializer_list< std::initializer_list< Element > >) -> state_transition< std::initializer_list< std::initializer_list< Element > > >
References input_control(), and state_transition().
transition()
template<typename Element > fcarouge::internal::transition (Element) -> transition< Element >
References observation(), and transition().
Referenced by input_control(), and transition().
Variable Documentation
filter
template<typename Filter > constexpr filter_deducer<Filter> fcarouge::internal::filter {} inline constexpr
Definition at line 270 of file factory.hpp.
{};
first_v
template<auto... Values> constexpr auto fcarouge::internal::first_v {first_value<Values...>::value} inline constexpr
Definition at line 310 of file utility.hpp.
{first_value<Values...>::value};
input
template<typename Type > input_t<Type> fcarouge::internal::input {} inline
Definition at line 131 of file type.hpp.
{};
output
template<typename Type > output_t<Type> fcarouge::internal::output {} inline
Definition at line 135 of file type.hpp.
{};
prediction_types
template<typename... Types> prediction_types_t<Types...> fcarouge::internal::prediction_types {} inline
Definition at line 219 of file type.hpp.
{};
size
template<typename Pack > constexpr auto fcarouge::internal::size {repack<Pack>::size} inline constexpr
Definition at line 307 of file utility.hpp.
{repack<Pack>::size};
update_types
template<typename... Types> update_types_t<Types...> fcarouge::internal::update_types {} inline
Definition at line 214 of file type.hpp.
{};