Kalman: fcarouge::kalman_internal Namespace Reference
fcarouge::kalman_internal Namespace Reference
Internal implementation details.
Classes
struct conditional_input
struct conditional_input< Filter >
struct conditional_input_control
struct conditional_input_control< Filter >
struct conditional_member_types
struct conditional_output_model
struct conditional_output_model< Filter >
struct conditional_output_uncertainty
struct conditional_output_uncertainty< Filter >
struct conditional_prediction_types
struct conditional_prediction_types< Filter >
struct conditional_process_uncertainty
struct conditional_process_uncertainty< Filter >
struct conditional_state_transition
struct conditional_state_transition< Filter >
struct conditional_update_types
struct conditional_update_types< Filter >
struct divides
Linear algebra divides expression type specialization point.
struct estimate_uncertainty
struct evaluates
Linear algebra evaluates override expression lazy evaluation specialization point.
struct filter_deducer
struct first_value
class function
class function< Result(Arguments...)>
struct function_traits
struct function_traits< Result(Type::*)(Arguments...) const >
struct input_control
struct input_t
struct minus
Type minus, subtraction expression type specialization point.
struct multiplies
Type multiplies expression type specialization point.
struct not_implemented
struct observation
struct output_model
struct output_t
struct output_uncertainty
struct prediction_types_t
struct process_uncertainty
struct repacker
struct repacker< Pack< Types... > >
struct state
struct state_transition
struct transition
struct transposes
Linear algebra transposes specialization point.
struct transposes< Type >
struct tupler
struct update_types_t
struct x_z_p_q_r
struct x_z_p_q_r_h_f
struct x_z_p_q_r_hh_us_ps
struct x_z_p_q_r_hh_us_ps< State, Output, std::tuple< UpdateTypes... >, std::tuple< PredictionTypes... > >
struct x_z_p_qq_rr_f
struct x_z_p_r
struct x_z_p_r_f
struct x_z_u_p_q_r
struct x_z_u_p_q_r_f_g_ps
struct x_z_u_p_q_r_f_g_ps< State, Output, Input, std::tuple< UpdateTypes... >, std::tuple< PredictionTypes... > >
struct x_z_u_p_q_r_h_f_g_us_ps
struct x_z_u_p_q_r_h_f_g_us_ps< State, Output, Input, std::tuple< UpdateTypes... >, std::tuple< PredictionTypes... > >
Typedefs
template<typename... Arguments>
using deduce_filter = std::invoke_result_t<filter_deducer<>, Arguments...>
template<typename Callable >
using function_traits_t
Functions
template<typename Callable >
function (Callable) -> function< function_traits_t< Callable > >
template<typename Result , typename... Arguments>
function (Result(Arguments...)) -> function< Result(Arguments...)>
template<typename Type >
state (Type) -> state< Type >
template<typename... Types>
state (Types... elements) -> state< std::remove_cvref_t< first< Types... > >[sizeof...(Types)]>
template<typename Element >
estimate_uncertainty (Element) -> estimate_uncertainty< Element >
template<typename Element >
estimate_uncertainty (std::initializer_list< std::initializer_list< Element > >) -> estimate_uncertainty< std::initializer_list< std::initializer_list< Element > > >
template<typename Element >
output_uncertainty (Element) -> output_uncertainty< Element >
template<typename Element >
output_uncertainty (std::initializer_list< std::initializer_list< Element > >) -> output_uncertainty< std::initializer_list< std::initializer_list< Element > > >
template<typename Element >
process_uncertainty (Element) -> process_uncertainty< Element >
template<typename Element >
process_uncertainty (std::initializer_list< std::initializer_list< Element > >) -> process_uncertainty< std::initializer_list< std::initializer_list< Element > > >
template<typename Element >
output_model (Element) -> output_model< Element >
template<typename Element >
output_model (std::initializer_list< std::initializer_list< Element > >) -> output_model< std::initializer_list< std::initializer_list< Element > > >
template<typename Element >
state_transition (Element) -> state_transition< Element >
template<typename Element >
state_transition (std::initializer_list< std::initializer_list< Element > >) -> state_transition< std::initializer_list< std::initializer_list< Element > > >
template<typename Element >
input_control (Element) -> input_control< Element >
template<typename Element >
input_control (std::initializer_list< std::initializer_list< Element > >) -> input_control< std::initializer_list< std::initializer_list< Element > > >
template<typename Element >
transition (Element) -> transition< Element >
template<typename Element >
observation (Element) -> observation< Element >
Functions
template<std::size_t Begin, std::size_t End, std::size_t Increment, typename Function >
constexpr void for_constexpr (Function &&function)
Compile-time for loop.
Variables
template<typename Filter >
constexpr filter_deducer< Filter > filter {}
template<typename Type >
input_t< Type > input {}
template<typename Type >
output_t< Type > output {}
template<typename... Types>
update_types_t< Types... > update_types {}
template<typename... Types>
prediction_types_t< Types... > prediction_types {}
Types
template<typename Lhs , typename Rhs >
using quotient
Divider helper type.
template<typename Type >
using evaluate = std::invoke_result_t<evaluates<Type>>
Evaluater helper type.
template<typename Type >
using transpose = std::invoke_result_t<transposes<Type>, const Type &>
Transposer helper type.
template<typename... Types>
using first = std::tuple_element_t<0, std::tuple<Types...>>
Unpack the first type of the type template parameter pack.
template<typename Type , std::size_t Size>
using tuple_n_type = typename tupler<Type, Size>::type
An alias for making a tuple of the same type.
template<typename Lhs , typename Rhs >
using product
Helper type to deduce the result type of the product.
template<typename Lhs , typename Rhs >
using difference
Helper type to deduce the result type of the minus, subtraction.
template<typename Lhs , typename Rhs >
using ᴀʙᵀ = evaluate<product<Lhs, evaluate<transpose<Rhs>>>>
The evaluated type of the ABᵀ expression.
template<typename Type >
auto t (const Type &value)
Transpose helper function.
Named Values
template<typename Pack >
using repack = repacker<Pack>::type
template<typename Pack >
constexpr std::size_t size {repacker<Pack>::size}
Size of tuple-like types.
template<auto... Values>
constexpr auto first_v {first_value<Values...>::value}
Unpack the first value of the non-type template parameter pack.
template<typename Type = double>
constexpr Type one
The one matrix.
template<arithmetic Arithmetic>
constexpr Arithmetic one< Arithmetic > {1}
The singleton one matrix specialization.
template<typename Type >
requires requires { Type::identity(); }
auto one< Type > {Type::Identity()}
template<typename Type = double>
constexpr Type zero
The zero matrix.
template<arithmetic Arithmetic>
constexpr Arithmetic zero< Arithmetic > {0}
The singleton zero matrix specialization.
template<typename Type >
requires requires { Type::zero(); }
auto zero< Type > {Type::Zero()}
Detailed Description
Internal implementation details.
Solely intended for this library usage. Do not rely on these details in your projects.
Typedef Documentation
ᴀʙᵀ
template<typename Lhs , typename Rhs > using fcarouge::kalman_internal::ᴀʙᵀ = evaluate<product<Lhs, evaluate<transpose<Rhs>>>>
The evaluated type of the ABᵀ expression.
Examples
kf_6x2x0_vehicle_location_unit.cpp.
Definition at line 298 of file utility.hpp.
deduce_filter
template<typename... Arguments> using fcarouge::kalman_internal::deduce_filter = std::invoke_result_t<filter_deducer<>, Arguments...>
Definition at line 359 of file factory.hpp.
difference
template<typename Lhs , typename Rhs > using fcarouge::kalman_internal::difference
Initial value:
    std::invoke_result_t<minus<Lhs, Rhs>, const Lhs &, const Rhs &>
Helper type to deduce the result type of the minus, subtraction.
Definition at line 293 of file utility.hpp.
evaluate
template<typename Type > using fcarouge::kalman_internal::evaluate = std::invoke_result_t<evaluates<Type>>
Evaluater helper type.
Examples
kf_6x2x0_vehicle_location_unit.cpp.
Definition at line 223 of file utility.hpp.
first
template<typename... Types> using fcarouge::kalman_internal::first = std::tuple_element_t<0, std::tuple<Types...>>
Unpack the first type of the type template parameter pack.
Shorthand for std::tuple_element_t<0, std::tuple<Types...>>.
Definition at line 255 of file utility.hpp.
function_traits_t
template<typename Callable > using fcarouge::kalman_internal::function_traits_t
Initial value:
    function_traits<decltype(&Callable::operator())>::type
Definition at line 94 of file function.hpp.
product
template<typename Lhs , typename Rhs > using fcarouge::kalman_internal::product
Initial value:
    std::invoke_result_t<multiplies<Lhs, Rhs>, const Lhs &, const Rhs &>
Helper type to deduce the result type of the product.
Examples
kf_1x1x0_building_height_unit.cpp.
Definition at line 282 of file utility.hpp.
quotient
template<typename Lhs , typename Rhs > using fcarouge::kalman_internal::quotient
Initial value:
    std::invoke_result_t<divides<Lhs, Rhs>, const Lhs &, const Rhs &>
Divider helper type.
Examples
kf_6x2x0_vehicle_location_unit.cpp.
Definition at line 213 of file utility.hpp.
repack
template<typename Pack > using fcarouge::kalman_internal::repack = repacker<Pack>::type
Definition at line 419 of file utility.hpp.
transpose
template<typename Type > using fcarouge::kalman_internal::transpose = std::invoke_result_t<transposes<Type>, const Type &>
Transposer helper type.
Definition at line 242 of file utility.hpp.
tuple_n_type
template<typename Type , std::size_t Size> using fcarouge::kalman_internal::tuple_n_type = typename tupler<Type, Size>::type
An alias for making a tuple of the same type.
Definition at line 272 of file utility.hpp.
Function Documentation
estimate_uncertainty() [1/2]
template<typename Element > fcarouge::kalman_internal::estimate_uncertainty (Element) -> estimate_uncertainty< Element >
estimate_uncertainty() [2/2]
template<typename Element > fcarouge::kalman_internal::estimate_uncertainty (std::initializer_list< std::initializer_list< Element > >) -> estimate_uncertainty< std::initializer_list< std::initializer_list< Element > > >
for_constexpr()
template<std::size_t Begin, std::size_t End, std::size_t Increment, typename Function > void fcarouge::kalman_internal::for_constexpr (Function && function) inline constexpr
Compile-time for loop.
Help compilers with non-type template parameters on members.
Definition at line 395 of file utility.hpp.
{
  if constexpr (Begin < End) {
    function(std::integral_constant<std::size_t, Begin>());
    for_constexpr<Begin + Increment, End, Increment>(
        std::forward<Function>(function));
  }
}
References for_constexpr(), and function().
Referenced by for_constexpr(), and std::formatter< Filter, Char >::format().
function() [1/2]
template<typename Callable > fcarouge::kalman_internal::function (Callable) -> function< function_traits_t< Callable > >
Referenced by for_constexpr().
function() [2/2]
template<typename Result , typename... Arguments> fcarouge::kalman_internal::function (Result(Arguments...)) -> function< Result(Arguments...)>
input_control() [1/2]
template<typename Element > fcarouge::kalman_internal::input_control (Element) -> input_control< Element >
input_control() [2/2]
template<typename Element > fcarouge::kalman_internal::input_control (std::initializer_list< std::initializer_list< Element > >) -> input_control< std::initializer_list< std::initializer_list< Element > > >
observation()
template<typename Element > fcarouge::kalman_internal::observation (Element) -> observation< Element >
output_model() [1/2]
template<typename Element > fcarouge::kalman_internal::output_model (Element) -> output_model< Element >
output_model() [2/2]
template<typename Element > fcarouge::kalman_internal::output_model (std::initializer_list< std::initializer_list< Element > >) -> output_model< std::initializer_list< std::initializer_list< Element > > >
output_uncertainty() [1/2]
template<typename Element > fcarouge::kalman_internal::output_uncertainty (Element) -> output_uncertainty< Element >
output_uncertainty() [2/2]
template<typename Element > fcarouge::kalman_internal::output_uncertainty (std::initializer_list< std::initializer_list< Element > >) -> output_uncertainty< std::initializer_list< std::initializer_list< Element > > >
process_uncertainty() [1/2]
template<typename Element > fcarouge::kalman_internal::process_uncertainty (Element) -> process_uncertainty< Element >
process_uncertainty() [2/2]
template<typename Element > fcarouge::kalman_internal::process_uncertainty (std::initializer_list< std::initializer_list< Element > >) -> process_uncertainty< std::initializer_list< std::initializer_list< Element > > >
state() [1/2]
template<typename Type > fcarouge::kalman_internal::state (Type) -> state< Type >
state() [2/2]
template<typename... Types> fcarouge::kalman_internal::state (Types... elements) -> state< std::remove_cvref_t< first< Types... > >[sizeof...(Types)]>
state_transition() [1/2]
template<typename Element > fcarouge::kalman_internal::state_transition (Element) -> state_transition< Element >
state_transition() [2/2]
template<typename Element > fcarouge::kalman_internal::state_transition (std::initializer_list< std::initializer_list< Element > >) -> state_transition< std::initializer_list< std::initializer_list< Element > > >
t()
template<typename Type > auto fcarouge::kalman_internal::t (const Type & value)
Transpose helper function.
Enable readable linear algebra notation.
Definition at line 247 of file utility.hpp.
{
  return transposes<Type>{}(value);
}
transition()
template<typename Element > fcarouge::kalman_internal::transition (Element) -> transition< Element >
Variable Documentation
filter
template<typename Filter > filter_deducer<Filter> fcarouge::kalman_internal::filter {} inline constexpr
Definition at line 356 of file factory.hpp.
{};
first_v
template<auto... Values> auto fcarouge::kalman_internal::first_v {first_value<Values...>::value} inline constexpr
Unpack the first value of the non-type template parameter pack.
Definition at line 433 of file utility.hpp.
{first_value<Values...>::value};
input
template<typename Type > input_t<Type> fcarouge::kalman_internal::input {} inline
Definition at line 138 of file type.hpp.
{};
one
template<typename Type = double> Type fcarouge::kalman_internal::one inline constexpr
Initial value:
{not_implemented<Type>{
    "Implement the linear algebra one-diagonal matrix for this type."}}
The one matrix.
User-defined matrix with all its diagonal elements equal to ones, and zeroes everywhere else. This matrix is also known as the identity matrix for square matrices of non-quantity scalar types.
Examples
kf_6x2x0_vehicle_location_unit.cpp.
Definition at line 454 of file utility.hpp.
                         {not_implemented<Type>{
    "Implement the linear algebra one-diagonal matrix for this type."}};
one< Arithmetic >
template<arithmetic Arithmetic> Arithmetic fcarouge::kalman_internal::one< Arithmetic > {1} inline constexpr
The singleton one matrix specialization.
Definition at line 458 of file utility.hpp.
{1};
one< Type >
template<typename Type > requires requires { Type::identity(); } auto fcarouge::kalman_internal::one< Type > {Type::Identity()} inline
Definition at line 462 of file utility.hpp.
{Type::Identity()};
output
template<typename Type > output_t<Type> fcarouge::kalman_internal::output {} inline
Definition at line 144 of file type.hpp.
{};
prediction_types
template<typename... Types> prediction_types_t<Types...> fcarouge::kalman_internal::prediction_types {} inline
Definition at line 238 of file type.hpp.
{};
size
template<typename Pack > std::size_t fcarouge::kalman_internal::size {repacker<Pack>::size} inline constexpr
Size of tuple-like types.
Convenient short form. In place of std::tuple_size_v.
Definition at line 425 of file utility.hpp.
{repacker<Pack>::size};
Referenced by std::formatter< Filter, Char >::format().
update_types
template<typename... Types> update_types_t<Types...> fcarouge::kalman_internal::update_types {} inline
Definition at line 233 of file type.hpp.
{};
zero
template<typename Type = double> Type fcarouge::kalman_internal::zero inline constexpr
Initial value:
{kalman_internal::not_implemented<Type>{
    "Implement the linear algebra zero matrix for this type."}}
The zero matrix.
User-defined.
Examples
kf_6x2x0_vehicle_location_unit.cpp, and kf_8x4x0_deep_sort_bounding_box.cpp.
Definition at line 472 of file utility.hpp.
                          {kalman_internal::not_implemented<Type>{
    "Implement the linear algebra zero matrix for this type."}};
zero< Arithmetic >
template<arithmetic Arithmetic> Arithmetic fcarouge::kalman_internal::zero< Arithmetic > {0} inline constexpr
The singleton zero matrix specialization.
Definition at line 477 of file utility.hpp.
{0};
zero< Type >
template<typename Type > requires requires { Type::zero(); } auto fcarouge::kalman_internal::zero< Type > {Type::Zero()} inline
Definition at line 481 of file utility.hpp.
{Type::Zero()};