Kalman: fcarouge::matrix< Type, Row, Column, Copyable > Struct Template Reference
fcarouge::matrix< Type, Row, Column, Copyable > Struct Template Reference
Coroutine lazy matrix.
#include <linalg.hpp>
Public Types
using generator = std::generator< Type >
using promise_type = std::coroutine_traits< generator >::promise_type
Public Member Functions
constexpr matrix ()
constexpr matrix (const matrix< Type, Row, Column, false > &other)
constexpr matrix (const matrix< Type, Row, Column, true > &other)
constexpr matrix & operator= (const matrix< Type, Row, Column, false > &other)
constexpr matrix & operator= (const matrix< Type, Row, Column, true > &other)
constexpr matrix (matrix< Type, Row, Column, false > &&other)
constexpr matrix (matrix< Type, Row, Column, true > &&other)
constexpr matrix & operator= (matrix< Type, Row, Column, false > &&other)
constexpr matrix & operator= (matrix< Type, Row, Column, true > &&other)
constexpr matrix (const std::same_as< Type > auto &...elements)
constexpr matrix (Type(&elements)[Row *Column])
template<typename... Types, auto... Columns>
requires (std::conjunction_v<std::is_same<Type, Types>...> && ((Columns == Column) && ... && true))
matrix (const Types(&...rows)[Columns])
constexpr matrix (std::generator< Type > other)
constexpr matrix (std::invocable auto other)
constexpr std::generator< Type > clone () const
constexpr explicit (false) operator matrix< Type
constexpr !Copyable () const
constexpr explicit (false) operator Type() const
explicit (false) operator std
constexpr Type operator[] (auto index) const
constexpr Type operator() (auto index) const
constexpr Type operator() (auto index) const
constexpr Type operator() (auto row, auto column) const
auto begin () const
auto end () const
constexpr matrix ()=default
constexpr matrix (const matrix &other)=default
constexpr matrix & operator= (const matrix &other)=default
constexpr matrix (matrix &&other)=default
constexpr matrix & operator= (matrix &&other)=default
constexpr matrix (const std::same_as< Type > auto &...elements)
constexpr matrix (const std::same_as< Type > auto &...elements)
constexpr matrix (Type(&elements)[Column])
constexpr matrix (Type(&elements)[Row])
template<typename... Types, auto... Columns>
requires (std::conjunction_v<std::is_same<Type, Types>...> && ((Columns == Column) && ... && true))
matrix (const Types(&...rows)[Columns])
constexpr matrix (std::initializer_list< std::initializer_list< Type > > rows)
constexpr explicit (false) operator Type() const
constexpr const Type & operator[] (auto index) const
constexpr const Type & operator[] (auto index) const
constexpr const Type & operator() (auto index) const
constexpr const Type & operator() (auto index) const
constexpr const Type & operator() (auto row, auto column) const
Public Attributes
constexpr Row
constexpr Column
generator genie
Type data [Row][Column] {}
Detailed Description
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false>
struct fcarouge::matrix< Type, Row, Column, Copyable >
Coroutine lazy matrix.
The matrix is a generator. A coroutine range. Lazily generated elements and computed operations. Commonalities with ranges.
Template Parameters
Type The matrix element type.
Row The number of rows of the matrix.
Column The number of columns of the matrix.
Copyable Whether the instance is fully lazy or deeply clones itself on copies. Useful for named values. May not be commonly used.
Note
Lifetime management with coroutine is tricky. The generators cannot use the lambda captures. The parameters of the lambda can however be copied to guarentee their lifetime for the usage of the generator. This technique is useful for initialization of the generator.
A design decision for the composed generator to be mutable, traded off for const member function API. Similar to the mutable mutex member practice.
Why genie? Because genies generate on demand.
Todo:
Explore and compare performance.
Explore optimization of heap allocations?
Explore constexpr support?
Explore verification of lazy evaluation?
Remove unecessary empty paramaters when MSVC supports lambda without them.
Definition at line 115 of file linalg.hpp.
Member Typedef Documentation
generator
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> using fcarouge::matrix< Type, Row, Column, Copyable >::generator = std::generator<Type>
Definition at line 269 of file linalg.hpp.
promise_type
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> using fcarouge::matrix< Type, Row, Column, Copyable >::promise_type = std::coroutine_traits<generator>::promise_type
Definition at line 270 of file linalg.hpp.
Constructor & Destructor Documentation
matrix() [1/19]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr fcarouge::matrix< Type, Row, Column, Copyable >::matrix () inline constexpr
Todo:
Report the ICE for generator construction in member declaration. Use constructor's initializer list for now.
Definition at line 118 of file linalg.hpp.
      : genie{[]() -> std::generator<Type> {
          for (auto k{Row * Column}; k > 0; --k) { // repeat(Type{}) | take(R*C)
            co_yield {};
          }
        }()} {}
References fcarouge::matrix< Type, Row, Column, Copyable >::Column, and fcarouge::matrix< Type, Row, Column, Copyable >::Row.
matrix() [2/19]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr fcarouge::matrix< Type, Row, Column, Copyable >::matrix (const matrix< Type, Row, Column, false > & other) inline constexpr
Definition at line 125 of file linalg.hpp.
      : genie{std::move(other.genie)} {}
matrix() [3/19]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr fcarouge::matrix< Type, Row, Column, Copyable >::matrix (const matrix< Type, Row, Column, true > & other) inline constexpr
Definition at line 128 of file linalg.hpp.
      : genie{other.clone()} {}
matrix() [4/19]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr fcarouge::matrix< Type, Row, Column, Copyable >::matrix (matrix< Type, Row, Column, false > && other) inline constexpr
Definition at line 143 of file linalg.hpp.
      : genie{std::move(other.genie)} {}
matrix() [5/19]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr fcarouge::matrix< Type, Row, Column, Copyable >::matrix (matrix< Type, Row, Column, true > && other) inline constexpr
Definition at line 146 of file linalg.hpp.
      : genie{other.clone()} {}
matrix() [6/19]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr fcarouge::matrix< Type, Row, Column, Copyable >::matrix (const std::same_as< Type > auto &... elements) inline explicit constexpr
Definition at line 159 of file linalg.hpp.
      : genie{[](auto... elements_copy) -> std::generator<Type> {
          (co_yield elements_copy, ...);
        }(elements...)} {}
matrix() [7/19]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr fcarouge::matrix< Type, Row, Column, Copyable >::matrix (Type(&) elements[Row *Column]) inline explicit constexpr
Definition at line 165 of file linalg.hpp.
      : genie{make_generator(std::to_array(elements))} {}
matrix() [8/19]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> template<typename... Types, auto... Columns> requires (std::conjunction_v<std::is_same<Type, Types>...> && ((Columns == Column) && ... && true)) fcarouge::matrix< Type, Row, Column, Copyable >::matrix (const Types(&...rows)[Columns]) inline
Definition at line 170 of file linalg.hpp.
      : genie{[](auto rows_copy) -> std::generator<Type> {
          for (auto &&row : rows_copy) {
            for (auto &&element : row) { // std::ranges::elements_of
              co_yield element;
            }
          }
        }(std::to_array({std::to_array(rows)...}))} {}
matrix() [9/19]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr fcarouge::matrix< Type, Row, Column, Copyable >::matrix (std::generator< Type > other) inline constexpr
Definition at line 181 of file linalg.hpp.
      : genie{std::move(other)} {}
matrix() [10/19]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr fcarouge::matrix< Type, Row, Column, Copyable >::matrix (std::invocable auto other) inline constexpr
Definition at line 184 of file linalg.hpp.
: genie{other()} {}
!Copyable()
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr fcarouge::matrix< Type, Row, Column, Copyable >::!Copyable () const inline
Definition at line 196 of file linalg.hpp.
{
    return clone();
  }
matrix() [11/19]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr fcarouge::matrix< Type, Row, Column, Copyable >::matrix () inline constexpr default
matrix() [12/19]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr fcarouge::matrix< Type, Row, Column, Copyable >::matrix (const matrix< Type, Row, Column, Copyable > & other) inline constexpr default
matrix() [13/19]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr fcarouge::matrix< Type, Row, Column, Copyable >::matrix (matrix< Type, Row, Column, Copyable > && other) inline constexpr default
matrix() [14/19]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr fcarouge::matrix< Type, Row, Column, Copyable >::matrix (const std::same_as< Type > auto &... elements) inline constexpr
Definition at line 74 of file linalg.hpp.
      : data{{elements...}} {}
matrix() [15/19]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr fcarouge::matrix< Type, Row, Column, Copyable >::matrix (const std::same_as< Type > auto &... elements) inline constexpr
Definition at line 78 of file linalg.hpp.
  {
    decltype(Row) i{0};
    ([&] { data[i++][0] = elements; }(), ...);
  }
References fcarouge::matrix< Type, Row, Column, Copyable >::data, and fcarouge::matrix< Type, Row, Column, Copyable >::Row.
matrix() [16/19]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr fcarouge::matrix< Type, Row, Column, Copyable >::matrix (Type(&) elements[Column]) inline explicit constexpr
Definition at line 85 of file linalg.hpp.
  {
    for (decltype(Column) j{0}; j < Column; ++j) {
      data[0][j] = elements[j];
    }
  }
References fcarouge::matrix< Type, Row, Column, Copyable >::Column, and fcarouge::matrix< Type, Row, Column, Copyable >::data.
matrix() [17/19]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr fcarouge::matrix< Type, Row, Column, Copyable >::matrix (Type(&) elements[Row]) inline explicit constexpr
Todo:
Perhaps this is too naive and can be improved?
Definition at line 93 of file linalg.hpp.
  {
    for (decltype(Row) i{0}; i < Row; ++i) {
      data[i][0] = elements[i];
    }
  }
References fcarouge::matrix< Type, Row, Column, Copyable >::data, and fcarouge::matrix< Type, Row, Column, Copyable >::Row.
matrix() [18/19]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> template<typename... Types, auto... Columns> requires (std::conjunction_v<std::is_same<Type, Types>...> && ((Columns == Column) && ... && true)) fcarouge::matrix< Type, Row, Column, Copyable >::matrix (const Types(&...rows)[Columns]) inline
Definition at line 103 of file linalg.hpp.
  {
    decltype(Row) i{0};
    (
        [&](const auto &row) {
          for (decltype(Column) j{0}; j < Column; ++j) {
            data[i][j] = row[j];
          }
          ++i;
        }(rows),
        ...);
  }
References fcarouge::matrix< Type, Row, Column, Copyable >::Column, fcarouge::matrix< Type, Row, Column, Copyable >::data, and fcarouge::matrix< Type, Row, Column, Copyable >::Row.
matrix() [19/19]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr fcarouge::matrix< Type, Row, Column, Copyable >::matrix (std::initializer_list< std::initializer_list< Type > > rows) inline explicit constexpr
Definition at line 118 of file linalg.hpp.
{
    for (decltype(Row) i{0}; const auto &row : rows) {
      for (decltype(Column) j{0}; const auto &element : row) {
        data[i][j] = element;
        ++j;
      }
      ++i;
    }
  }
References fcarouge::matrix< Type, Row, Column, Copyable >::Column, fcarouge::matrix< Type, Row, Column, Copyable >::data, and fcarouge::matrix< Type, Row, Column, Copyable >::Row.
Member Function Documentation
begin()
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> auto fcarouge::matrix< Type, Row, Column, Copyable >::begin () const inline
Definition at line 273 of file linalg.hpp.
{ return genie.begin(); }
clone()
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr std::generator< Type > fcarouge::matrix< Type, Row, Column, Copyable >::clone () const inline constexpr
Definition at line 186 of file linalg.hpp.
{
    std::array<Type, Row * Column> elements; // std::ranges::to
    std::ranges::copy(genie, elements.begin());
    genie = make_generator(elements);
    return make_generator(elements);
  }
References fcarouge::make_generator().
Referenced by fcarouge::matrix< Type, Row, Column, Copyable >::operator=(), and fcarouge::matrix< Type, Row, Column, Copyable >::operator=().
end()
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> auto fcarouge::matrix< Type, Row, Column, Copyable >::end () const inline
Definition at line 274 of file linalg.hpp.
{ return genie.end(); }
explicit() [1/4]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr fcarouge::matrix< Type, Row, Column, Copyable >::explicit (false) inline constexpr
explicit() [2/4]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> fcarouge::matrix< Type, Row, Column, Copyable >::explicit (false) inline
Definition at line 210 of file linalg.hpp.
{
    co_yield std::ranges::elements_of(genie);
  }
  [[nodiscard]] inline constexpr Type operator[](auto index) const
    requires(Row != 1 && Column == 1)
  {
    std::array<Type, Row * Column> elements; // std::ranges::to
    std::ranges::copy(genie, elements.begin());
    genie = make_generator(elements);
    return elements[index];
  }
explicit() [3/4]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr fcarouge::matrix< Type, Row, Column, Copyable >::explicit (false) const inline constexpr
Definition at line 200 of file linalg.hpp.
  {
    Type element{*genie.begin()};
    genie = make_generator(element);
    return element;
  }
References fcarouge::make_generator().
explicit() [4/4]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr fcarouge::matrix< Type, Row, Column, Copyable >::explicit (false) const inline constexpr
Definition at line 130 of file linalg.hpp.
  {
    return data[0][0];
  }
References fcarouge::matrix< Type, Row, Column, Copyable >::data.
operator()() [1/6]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr Type fcarouge::matrix< Type, Row, Column, Copyable >::operator() (auto index) const inline constexpr
Definition at line 236 of file linalg.hpp.
  {
    std::array<Type, Row * Column> elements; // std::ranges::to
    std::ranges::copy(genie, elements.begin());
    genie = make_generator(elements);
    return elements[index];
  }
References fcarouge::make_generator().
operator()() [2/6]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr Type fcarouge::matrix< Type, Row, Column, Copyable >::operator() (auto index) const inline constexpr
Definition at line 247 of file linalg.hpp.
  {
    std::array<Type, Row * Column> elements; // std::ranges::to
    std::ranges::copy(genie, elements.begin());
    genie = make_generator(elements);
    return elements[index];
  }
References fcarouge::make_generator().
operator()() [3/6]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr const Type & fcarouge::matrix< Type, Row, Column, Copyable >::operator() (auto index) const inline constexpr
Definition at line 148 of file linalg.hpp.
  {
    return data[index][0];
  }
References fcarouge::matrix< Type, Row, Column, Copyable >::data.
operator()() [4/6]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr const Type & fcarouge::matrix< Type, Row, Column, Copyable >::operator() (auto index) const inline constexpr
Definition at line 154 of file linalg.hpp.
  {
    return data[0][index];
  }
References fcarouge::matrix< Type, Row, Column, Copyable >::data.
operator()() [5/6]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr Type fcarouge::matrix< Type, Row, Column, Copyable >::operator() (auto row, auto column) const inline constexpr
Todo:
Don't evaluate unless needed. How to do? Some kind of recursive genie recomposer?
Definition at line 260 of file linalg.hpp.
{
    std::array<Type, Row * Column> elements; // std::ranges::to
    std::ranges::copy(genie, elements.begin());
    genie = make_generator(elements);
    return elements[row * Column + column];
  }
References fcarouge::make_generator().
operator()() [6/6]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr const Type & fcarouge::matrix< Type, Row, Column, Copyable >::operator() (auto row, auto column) const inline constexpr
Definition at line 160 of file linalg.hpp.
{
    return data[row][column];
  }
References fcarouge::matrix< Type, Row, Column, Copyable >::data.
operator=() [1/6]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr matrix & fcarouge::matrix< Type, Row, Column, Copyable >::operator= (const matrix< Type, Row, Column, Copyable > & other) inline constexpr default
operator=() [2/6]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr matrix & fcarouge::matrix< Type, Row, Column, Copyable >::operator= (const matrix< Type, Row, Column, false > & other) inline constexpr
Definition at line 132 of file linalg.hpp.
{
    genie = std::move(other.genie);
    return *this;
  }
operator=() [3/6]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr matrix & fcarouge::matrix< Type, Row, Column, Copyable >::operator= (const matrix< Type, Row, Column, true > & other) inline constexpr
Definition at line 138 of file linalg.hpp.
{
    genie = other.clone();
    return *this;
  }
References fcarouge::matrix< Type, Row, Column, Copyable >::clone().
operator=() [4/6]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr matrix & fcarouge::matrix< Type, Row, Column, Copyable >::operator= (matrix< Type, Row, Column, Copyable > && other) inline constexpr default
operator=() [5/6]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr matrix & fcarouge::matrix< Type, Row, Column, Copyable >::operator= (matrix< Type, Row, Column, false > && other) inline constexpr
Definition at line 149 of file linalg.hpp.
{
    genie = std::move(other.genie);
    return *this;
  }
operator=() [6/6]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr matrix & fcarouge::matrix< Type, Row, Column, Copyable >::operator= (matrix< Type, Row, Column, true > && other) inline constexpr
Definition at line 154 of file linalg.hpp.
{
    genie = other.clone();
    return *this;
  }
References fcarouge::matrix< Type, Row, Column, Copyable >::clone().
operator[]() [1/3]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr Type fcarouge::matrix< Type, Row, Column, Copyable >::operator[] (auto index) const inline constexpr
Definition at line 225 of file linalg.hpp.
  {
    std::array<Type, Row * Column> elements; // std::ranges::to
    std::ranges::copy(genie, elements.begin());
    genie = make_generator(elements);
    return elements[index];
  }
References fcarouge::make_generator().
operator[]() [2/3]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr const Type & fcarouge::matrix< Type, Row, Column, Copyable >::operator[] (auto index) const inline constexpr
Definition at line 136 of file linalg.hpp.
  {
    return data[index][0];
  }
References fcarouge::matrix< Type, Row, Column, Copyable >::data.
operator[]() [3/3]
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr const Type & fcarouge::matrix< Type, Row, Column, Copyable >::operator[] (auto index) const inline constexpr
Definition at line 142 of file linalg.hpp.
  {
    return data[0][index];
  }
References fcarouge::matrix< Type, Row, Column, Copyable >::data.
Member Data Documentation
Column
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr fcarouge::matrix< Type, Row, Column, Copyable >::Column
Definition at line 196 of file linalg.hpp.
Referenced by fcarouge::matrix< Type, Row, Column, Copyable >::matrix(), fcarouge::matrix< Type, Row, Column, Copyable >::matrix(), fcarouge::matrix< Type, Row, Column, Copyable >::matrix(), and fcarouge::matrix< Type, Row, Column, Copyable >::matrix().
data
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> Type fcarouge::matrix< Type, Row, Column, Copyable >::data[Row][Column] {}
Definition at line 165 of file linalg.hpp.
{};
Referenced by fcarouge::matrix< Type, Row, Column, Copyable >::explicit(), fcarouge::matrix< Type, Row, Column, Copyable >::matrix(), fcarouge::matrix< Type, Row, Column, Copyable >::matrix(), fcarouge::matrix< Type, Row, Column, Copyable >::matrix(), fcarouge::matrix< Type, Row, Column, Copyable >::matrix(), fcarouge::matrix< Type, Row, Column, Copyable >::matrix(), fcarouge::matrix< Type, Row, Column, Copyable >::operator()(), fcarouge::matrix< Type, Row, Column, Copyable >::operator()(), and fcarouge::matrix< Type, Row, Column, Copyable >::operator[]().
genie
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> generator fcarouge::matrix< Type, Row, Column, Copyable >::genie mutable
Definition at line 276 of file linalg.hpp.
Row
template<typename Type = double, auto Row = 1, auto Column = 1, bool Copyable = false> constexpr fcarouge::matrix< Type, Row, Column, Copyable >::Row
Definition at line 196 of file linalg.hpp.
Referenced by fcarouge::matrix< Type, Row, Column, Copyable >::matrix(), fcarouge::matrix< Type, Row, Column, Copyable >::matrix(), fcarouge::matrix< Type, Row, Column, Copyable >::matrix(), fcarouge::matrix< Type, Row, Column, Copyable >::matrix(), and fcarouge::matrix< Type, Row, Column, Copyable >::matrix().
The documentation for this struct was generated from the following files:
/github/workspace/linalg/lazy/fcarouge/linalg.hpp
/github/workspace/linalg/naive/fcarouge/linalg.hpp