Kalman: fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments > Struct Template Reference
fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments > Struct Template Reference
#include <kalman.hpp>
Public Types
Public Member Types
using state = State
Type of the state estimate vector X.
using output = Output
Type of the observation vector Z.
using input = Input
Type of the control vector U.
using estimate_uncertainty = std::decay_t< std::invoke_result_t< Divide, State, State > >
Type of the estimated covariance matrix P.
using process_uncertainty = std::decay_t< std::invoke_result_t< Divide, State, State > >
Type of the process noise covariance matrix Q.
using output_uncertainty = std::decay_t< std::invoke_result_t< Divide, Output, Output > >
Type of the observation, measurement noise covariance matrix R.
using state_transition = std::decay_t< std::invoke_result_t< Divide, State, State > >
Type of the state transition matrix F.
using output_model = std::decay_t< std::invoke_result_t< Divide, Output, State > >
Type of the observation transition matrix H.
using input_control = std::decay_t< std::invoke_result_t< Divide, State, Input > >
Type of the control transition matrix G.
using gain = std::decay_t< std::invoke_result_t< Transpose, output_model > >
Type of the gain matrix K.
using innovation = output
Type of the innovation vector Y.
using innovation_uncertainty = output_uncertainty
Type of the innovation uncertainty matrix S.
Public Member Functions
Public Member Functions
constexpr void update (const auto &...output_z)
constexpr void predict (const PredictionArguments &...arguments, const auto &...input_u)
constexpr void predict (const PredictionArguments &...arguments)
Public Attributes
Public Member Variables
state x { 0 * Identity().template operator()<state>() }
The state estimate vector x.
estimate_uncertainty p
The estimate uncertainty, covariance matrix P.
process_uncertainty q
output_uncertainty r
output_model h { Identity().template operator()<output_model>() }
state_transition f { Identity().template operator()<state_transition>() }
input_control g { Identity().template operator()<input_control>() }
gain k { Identity().template operator()<gain>() }
innovation y { 0 * Identity().template operator()<innovation>() }
innovation_uncertainty s
output z { 0 * Identity().template operator()<output>() }
Public Member Function Objects
std::function< output_model(const state &)> observation_state_h
Compute the state observation H matrix.
std::function< output_uncertainty(const state &, const output &)> noise_observation_r
Compute observation noise R matrix.
std::function< state_transition(const state &, const PredictionArguments &...)> transition_state_f
Compute the state transition F matrix.
std::function< process_uncertainty(const state &, const PredictionArguments &...)> noise_process_q
Compute process noise Q matrix.
std::function< input_control(const PredictionArguments &...)> transition_control_g
Compute control transition G matrix.
std::function< state(const state &, const PredictionArguments &...)> transition
State transition function f.
std::function< output(const state &)> observation
State observation function h.
Transpose transpose
Divide divide
Symmetrize symmetrize
Identity identity
Detailed Description
template<typename State, typename Output, typename Input, typename Transpose, typename Symmetrize, typename Divide, typename Identity, typename... PredictionArguments>
struct fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >
Definition at line 53 of file kalman.hpp.
Member Typedef Documentation
estimate_uncertainty
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> using fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::estimate_uncertainty = std::decay_t<std::invoke_result_t<Divide, State, State> >
Type of the estimated covariance matrix P.
Also known as Σ.
Definition at line 71 of file kalman.hpp.
gain
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> using fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::gain = std::decay_t<std::invoke_result_t<Transpose, output_model> >
Type of the gain matrix K.
Definition at line 101 of file kalman.hpp.
innovation
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> using fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::innovation = output
Type of the innovation vector Y.
Definition at line 104 of file kalman.hpp.
innovation_uncertainty
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> using fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::innovation_uncertainty = output_uncertainty
Type of the innovation uncertainty matrix S.
Definition at line 107 of file kalman.hpp.
input
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> using fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::input = Input
Type of the control vector U.
Definition at line 66 of file kalman.hpp.
input_control
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> using fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::input_control = std::decay_t<std::invoke_result_t<Divide, State, Input> >
Type of the control transition matrix G.
Also known as B.
Definition at line 97 of file kalman.hpp.
output
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> using fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::output = Output
Type of the observation vector Z.
Also known as Y or O.
Definition at line 63 of file kalman.hpp.
output_model
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> using fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::output_model = std::decay_t<std::invoke_result_t<Divide, Output, State> >
Type of the observation transition matrix H.
Also known as C.
Definition at line 91 of file kalman.hpp.
output_uncertainty
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> using fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::output_uncertainty = std::decay_t<std::invoke_result_t<Divide, Output, Output> >
Type of the observation, measurement noise covariance matrix R.
Definition at line 79 of file kalman.hpp.
process_uncertainty
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> using fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::process_uncertainty = std::decay_t<std::invoke_result_t<Divide, State, State> >
Type of the process noise covariance matrix Q.
Definition at line 75 of file kalman.hpp.
state
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> using fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::state = State
Type of the state estimate vector X.
Definition at line 58 of file kalman.hpp.
state_transition
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> using fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::state_transition = std::decay_t<std::invoke_result_t<Divide, State, State> >
Type of the state transition matrix F.
Also known as Φ or A.
Definition at line 85 of file kalman.hpp.
Member Function Documentation
predict() [1/2]
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::predict (const PredictionArguments &... arguments) inline constexpr
Definition at line 287 of file kalman.hpp.
  {
    f = transition_state_f(x, arguments...);
    q = noise_process_q(x, arguments...);
    x = transition(x, arguments...);
    p = symmetrize(estimate_uncertainty{ f * p * transpose(f) + q });
  }
References fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::f, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::noise_process_q, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::p, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::q, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::symmetrize, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::transition, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::transition_state_f, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::transpose, and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::x.
predict() [2/2]
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::predict (const PredictionArguments &... arguments, const auto &... input_u) inline constexpr
Todo:
F would be the predict Jacobian(x) extended?
Would x = extended_ff(x, u) be extended?
Definition at line 275 of file kalman.hpp.
  {
    const auto u{ input{ input_u... } };
    f = transition_state_f(x, arguments...);
    q = noise_process_q(x, arguments...);
    g = transition_control_g(arguments...);
    x = f * x + g * u;
    p = symmetrize(estimate_uncertainty{ f * p * transpose(f) + q });
  }
References fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::f, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::g, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::noise_process_q, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::p, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::q, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::symmetrize, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::transition_control_g, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::transition_state_f, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::transpose, and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::x.
Referenced by fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::operator()().
update()
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> constexpr void fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::update (const auto &... output_z) inline constexpr
Todo:
Do we want to store i - k * h in a temporary result for reuse? Or does the compiler/linker do it for us?
H would be the observe Jacobian(x) extended?
Would innovation y = z - extended_hh(x) be extended?
Definition at line 257 of file kalman.hpp.
  {
    const auto i{ identity.template operator()<estimate_uncertainty>() };
    z = output{ output_z... };
    h = observation_state_h(x);
    r = noise_observation_r(x, z);
    s = h * p * transpose(h) + r;
    k = divide(p * transpose(h), s);
    // Do we want to support custom y = output_difference(z, observation(x))?
    y = z - observation(x);
    x = x + k * y;
    p = symmetrize(estimate_uncertainty{
        (i - k * h) * p * transpose(i - k * h) + k * r * transpose(k) });
  }
References fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::divide, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::h, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::k, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::noise_observation_r, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::observation, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::observation_state_h, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::p, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::r, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::s, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::symmetrize, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::transpose, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::x, fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::y, and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::z.
Referenced by fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::operator()().
Member Data Documentation
divide
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> Divide fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::divide
Definition at line 244 of file kalman.hpp.
Referenced by fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::update().
f
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> state_transition fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::f { Identity().template operator()<state_transition>() }
Definition at line 134 of file kalman.hpp.
Referenced by fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::predict().
g
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> input_control fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::g { Identity().template operator()<input_control>() }
Todo:
Should G be initialized to all ones?
Definition at line 137 of file kalman.hpp.
Referenced by fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::predict().
h
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> output_model fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::h { Identity().template operator()<output_model>() }
Todo:
Should H be initialized to all ones?
Definition at line 133 of file kalman.hpp.
Referenced by fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::update().
identity
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> Identity fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::identity
Definition at line 246 of file kalman.hpp.
k
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> gain fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::k { Identity().template operator()<gain>() }
Todo:
Should K be initialized to all ones?
Definition at line 140 of file kalman.hpp.
Referenced by fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::update().
noise_observation_r
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> std::function<output_uncertainty(const state &, const output &)> fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::noise_observation_r
Initial value:
{ [this](const state &x,
                                  const output &z) -> output_uncertainty {
        static_cast<void>(x);
        static_cast<void>(z);
        return r;
      } }
Compute observation noise R matrix.
Definition at line 173 of file kalman.hpp.
Referenced by fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::r(), and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::update().
noise_process_q
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> std::function<process_uncertainty(const state &, const PredictionArguments &...)> fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::noise_process_q
Initial value:
{
        [this](const state &x,
               const PredictionArguments &...arguments) -> process_uncertainty {
          static_cast<void>(x);
          (static_cast<void>(arguments), ...);
          return q;
        }
      }
Compute process noise Q matrix.
Definition at line 202 of file kalman.hpp.
Referenced by fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::predict(), and fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::q().
observation
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> std::function<output(const state &)> fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::observation
Initial value:
{
    [this](const state &x) -> output { return h * x; }
  }
State observation function h.
For linear system h(x) = H * X. For non-linear system, or extended filter, the client implements a linearization of the observation function hand the state observation H matrix is the Jacobian of the state observation function.
Definition at line 239 of file kalman.hpp.
Referenced by fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::observation(), and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::update().
observation_state_h
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> std::function<output_model(const state &)> fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::observation_state_h
Initial value:
{
    [this](const state &x) -> output_model {
      static_cast<void>(x);
      return h;
    }
  }
Compute the state observation H matrix.
The state observation H is also known as C. For non-linear system, or extended filter, H is the Jacobian of the state observation function. H = ∂h/∂X = ∂hj/∂xi that is each row i contains the derivatives of the state observation function for every element j in the state vector X.
Todo:
Should we pass through the reference to the state x or have the user access it through k.x() when needed? Where does the practical/performance tradeoff leans toward? For the general case? For the specialized cases? Same question applies to other parameters.
Definition at line 164 of file kalman.hpp.
Referenced by fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::h(), and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::update().
p
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> estimate_uncertainty fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::p
Initial value:
{
    Identity().template operator()<estimate_uncertainty>()
  }
The estimate uncertainty, covariance matrix P.
The estimate uncertainty, covariance is also known as Σ.
Definition at line 122 of file kalman.hpp.
Referenced by fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::predict(), and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::update().
q
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> process_uncertainty fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::q
Initial value:
{
    0 * Identity().template operator()<process_uncertainty>()
  }
Definition at line 126 of file kalman.hpp.
Referenced by fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::predict().
r
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> output_uncertainty fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::r
Initial value:
{ 0 *
                        Identity().template operator()<output_uncertainty>() }
Definition at line 129 of file kalman.hpp.
Referenced by fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::update().
s
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> innovation_uncertainty fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::s
Initial value:
{
    Identity().template operator()<innovation_uncertainty>()
  }
Definition at line 142 of file kalman.hpp.
Referenced by fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::update().
symmetrize
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> Symmetrize fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::symmetrize
Definition at line 245 of file kalman.hpp.
Referenced by fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::predict(), and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::update().
transition
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> std::function<state(const state &, const PredictionArguments &...)> fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::transition
Initial value:
{ [this](const state &x,
                         const PredictionArguments &...arguments) -> state {
        (static_cast<void>(arguments), ...);
        return f * x;
      } }
State transition function f.
For linear system f(x) = F * X. For non-linear system, or extended filter, the client implements a linearization of the transition function f and the state transition F matrix is the Jacobian of the state transition function.
Definition at line 227 of file kalman.hpp.
Referenced by fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::predict(), and fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::transition().
transition_control_g
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> std::function<input_control(const PredictionArguments &...)> fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::transition_control_g
Initial value:
{
        [this](const PredictionArguments &...arguments) -> input_control {
          (static_cast<void>(arguments), ...);
          return g;
        }
      }
Compute control transition G matrix.
Definition at line 213 of file kalman.hpp.
Referenced by fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::g(), and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::predict().
transition_state_f
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> std::function<state_transition(const state &, const PredictionArguments &...)> fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::transition_state_f
Initial value:
{
        [this](const state &x,
               const PredictionArguments &...arguments) -> state_transition {
          static_cast<void>(x);
          (static_cast<void>(arguments), ...);
          return f;
        }
      }
Compute the state transition F matrix.
The state transition F matrix is also known as Φ or A. For non-linear system, or extended filter, F is the Jacobian of the state transition function. F = ∂f/∂X = ∂fj/∂xi that is each row i contains the derivatives of the state transition function for every element j in the state vector X.
Todo:
Pass the arguments by universal reference?
Definition at line 190 of file kalman.hpp.
Referenced by fcarouge::kalman< Type, State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::f(), and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::predict().
transpose
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> Transpose fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::transpose
Definition at line 243 of file kalman.hpp.
Referenced by fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::predict(), and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::update().
x
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> state fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::x { 0 * Identity().template operator()<state>() }
The state estimate vector x.
Todo:
Is there a simpler, more portable way to get a zero initialization?
Definition at line 117 of file kalman.hpp.
Referenced by fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::predict(), and fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::update().
y
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> innovation fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::y { 0 * Identity().template operator()<innovation>() }
Definition at line 141 of file kalman.hpp.
Referenced by fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::update().
z
template<typename State , typename Output , typename Input , typename Transpose , typename Symmetrize , typename Divide , typename Identity , typename... PredictionArguments> output fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::z { 0 * Identity().template operator()<output>() }
Definition at line 145 of file kalman.hpp.
Referenced by fcarouge::internal::kalman< State, Output, Input, Transpose, Symmetrize, Divide, Identity, PredictionArguments >::update().
The documentation for this struct was generated from the following file:
include/fcarouge/internal/kalman.hpp