name: "Bloaty"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
    - name: Install
      run: |
        ( cd /tmp ;
          git clone --depth 1 https://github.com/google/bloaty.git ;
          ( cd bloaty ;
            mkdir build ;
            ( cd build ;
              cmake -B build -G Ninja -S ..
              cmake --build build
              cmake --build build --target install ; ) ) )
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make
