name: "ClangFormat"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
    - name: Verify
      run: find . -iname *.hpp -o -iname *.cpp -o -iname support/** | xargs clang-format-14 --Werror --dry-run --verbose -style=file
