name: "ClangFormat"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Install
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 15 all
    - name: Verify
      run: find . -iname "*.hpp" -o -iname "*.cpp" -o -iwholename "./support/format" | xargs clang-format-15 --Werror --dry-run --verbose -style=file
