name: 'Coverage: Comment'

on:
  workflow_run:
    workflows: ['Coverage']
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      pull-requests: write
    steps:
      - name: 'Coverage: Artifacts'
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: coverage-artifact
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: 'Read Artifact Data'
        id: read-data
        run: |
          PR_NUMBER=$(cat pull_request_id.txt)
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "coverage<<$EOF" >> $GITHUB_OUTPUT
          cat coverage.txt >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
      - name: 'Coverage: Comment'
        if: steps.read-data.outputs.pr_number != ''
        uses: mshick/add-pr-comment@64b8e914979889d746c99dea15a76e77ef64580a # v3.10.0.8.3.10.0
        with:
          issue: ${{ steps.read-data.outputs.pr_number }}
          message: ${{ steps.read-data.outputs.coverage }}
          preformatted: true
          refresh-message-position: true
