name: "CppCheck"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Install
      run: pip install cpplint
    - name: Verify
      run: |
        cppcheck \
          --enable=all \
          --error-exitcode=1 \
          --verbose \
          -I include \
          .
