name: "Install: Windows 2019 MSVC"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Install
      uses: ilammy/msvc-dev-cmd@v1.12.0
    - name: Version
      run: cl
    - name: Build
      run: |
        cmake -B "build" .
        cmake --build "build" --config "Release" --parallel 4
        cmake --install "build" --config "Release"
