name: "Install: Ubuntu 22.04 GCC"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Build
      run: |
        cmake -B "build" .
        cmake --build "build" --parallel 4
        sudo cmake --install "build"
