name: 'Test Memory: Valgrind'

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
  schedule:
  - cron: '0 0 * * */5'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - name: 'Install: Latest CMake'
      uses: ssrobins/install-cmake@da13ba26f50a41d3b03cfe8ca7265903f04a8932 # v1.0.0
    - name: 'Install'
      run: sudo apt update && sudo apt install valgrind
    - name: Build
      env:
        CXX: 'g++-14'
        CC: 'gcc-14'
        COMMAND: 'valgrind --error-exitcode=1 --leak-check=full --track-origins=yes'
      run: cmake -S . -B 'build'
    - name: 'Build'
      run: cmake --build 'build' --verbose --parallel 4
    - name: 'Test'
      run: ctest --test-dir 'build' --timeout 10 --tests-regex 'kalman' --verbose --parallel 4
