name: "Package: Ubuntu 22.04 Clang"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Build
      run: |
        export CC=clang
        export CXX=clang++
        cmake -B "build" .
        cmake --build "build" --target "package" --parallel 4
        cmake --build "build" --target "package_source" --parallel 4
