name: 'Sanitizer'

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
  schedule:
  - cron: '0 0 * * */5'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
        - name: 'Address'
          cpp_flags: '-fsanitize=address -O0 -g -fno-sanitize-recover=all -fno-omit-frame-pointer'
          ld_flags: ''
          run_flags: 'ASAN_OPTIONS=verbosity=1:abort_on_error=1:strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1'
        - name: 'Control Flow Integrity'
          cpp_flags: '-fsanitize=cfi -fno-sanitize-trap=cfi -flto=thin -fvisibility=hidden -O1 -g -fno-sanitize-recover=all -fno-omit-frame-pointer'
          ld_flags: '-fuse-ld=lld'
          run_flags: 'UBSAN_OPTIONS=verbosity=1:abort_on_error=1'
        - name: 'Integer'
          cpp_flags: '-fsanitize=integer,implicit-conversion,nullability -O0 -g -fno-sanitize-recover=all -fno-omit-frame-pointer'
          ld_flags: ''
          run_flags: 'UBSAN_OPTIONS=verbosity=1:abort_on_error=1'
        - name: 'Leak'
          cpp_flags: '-fsanitize=leak -O0 -g -fno-sanitize-recover=all -fno-omit-frame-pointer'
          ld_flags: ''
          run_flags: 'LSAN_OPTIONS=verbosity=1:abort_on_error=1'
        - name: 'Thread'
          cpp_flags: '-fsanitize=thread -O0 -g -fno-sanitize-recover=all -fno-omit-frame-pointer'
          ld_flags: ''
          run_flags: 'TSAN_OPTIONS=verbosity=1:abort_on_error=1'
        - name: 'Type'
          cpp_flags: '-fsanitize=type -O0 -g -fno-sanitize-recover=all -fno-omit-frame-pointer -fno-optimize-sibling-calls'
          ld_flags: ''
          run_flags: 'TYSAN_OPTIONS=verbosity=1:abort_on_error=1:print_stacktrace=1'
        - name: 'Undefined'
          cpp_flags: '-fsanitize=undefined -O0 -g -fno-sanitize-recover=all -fno-omit-frame-pointer'
          ld_flags: ''
          run_flags: 'UBSAN_OPTIONS=verbosity=1:abort_on_error=1'
    name: '${{ matrix.sanitizer.name }}'
    runs-on: ubuntu-26.04
    permissions:
      contents: read
    env:
      CXXFLAGS: '${{ matrix.sanitizer.cpp_flags }}'
      LDFLAGS: '${{ matrix.sanitizer.ld_flags }}'
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
      with:
        egress-policy: audit
    - name: 'Checkout'
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: 'Install: Latest CMake'
      uses: lukka/get-cmake@fffaaafeea488556c2c12dad60690008bc1caacb # v4.4.2
    - name: 'Install: LLD'
      run: |
        sudo apt update
        sudo apt install -y "lld-21"
    - name: 'Configure'
      env:
        CXX: 'clang++-21'
        CC: 'clang-21'
      run: cmake -S . -B 'build'
    - name: 'Build'
      run: cmake --build 'build' --verbose --parallel 4
    - name: 'Test'
      run: ${{ matrix.sanitizer.run_flags }} ctest --test-dir 'build' --timeout 30 --verbose --parallel 1
