name: "Test Address: Sanitizer"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Update
      run: sudo apt update
    - name: Install
      run: |
        sudo apt install gcc-12 g++-12
        ( cd /tmp
          git clone --depth 1 https://gitlab.com/libeigen/eigen.git
          mkdir eigen/build
          ( cd eigen/build
            cmake ..
            cmake --build . --parallel
            sudo cmake --install . ) )
        ( cd /tmp
          git clone --depth 1 https://github.com/fmtlib/fmt.git
          mkdir fmt/build
          ( cd fmt/build
            cmake ..
            cmake --build . --parallel
            sudo cmake --install . ) )
        ( cd /tmp
          git clone --depth 1 https://github.com/kokkos/mdspan.git
          mkdir mdspan/build
          ( cd mdspan/build
            cmake ..
            cmake --build . --parallel
            sudo cmake --install . ) )
        ( cd /tmp
          git clone --depth 1 https://github.com/kokkos/stdBLAS.git
          mkdir stdBLAS/build
          ( cd stdBLAS/build
            cmake ..
            cmake --build . --parallel
            sudo cmake --install . ) )
        ( cd /tmp
          git clone --depth 1 https://github.com/BobSteagall/wg21.git
          mkdir wg21/build
          ( cd wg21/build
            cmake ..
            sudo cmake --install . ) )
    - name: Build
      run: |
        gcc-12 \
          sample/*.cpp test/*.cpp source/*.cpp \
          -Iinclude -I/usr/local/include/eigen3 -Isupport \
          -std=c++23 -g -fsanitize=address -fsanitize-address-use-after-scope -fno-omit-frame-pointer -lstdc++ -lm -lfmt
    - name: Test
      run: ASAN_OPTIONS=verbosity=2:strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1 ./a.out
