name: 'Sanitizer'

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
  schedule:
  - cron: '0 0 * * */5'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
        - name: 'Address'
          cpp_flags: '-g -O0 -fsanitize=address'
          run_flags: 'ASAN_OPTIONS=verbosity=1:strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1'
        - name: 'Leak'
          cpp_flags: '-g -O0 -fsanitize=leak'
          run_flags: 'LSAN_OPTIONS=verbosity=1'
        - name: 'Thread'
          cpp_flags: '-g -O0 -fsanitize=thread'
          run_flags: 'TSAN_OPTIONS=verbosity=1'
        - name: 'Undefined'
          cpp_flags: '-g -O0 -fsanitize=undefined'
          run_flags: 'UBSAN_OPTIONS=verbosity=1'
    name: '${{ matrix.sanitizer.name }}'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    env:
      CXXFLAGS: '${{ matrix.sanitizer.cpp_flags }}'
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit
    - name: 'Checkout'
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: 'Install: Latest CMake'
      uses: ssrobins/install-cmake@da13ba26f50a41d3b03cfe8ca7265903f04a8932 # v1.0.0
    - name: 'Configure'
      env:
        CXX: 'g++-14'
        CC: 'gcc-14'
      run: cmake -S . -B 'build'
    - name: 'Build'
      run: cmake --build 'build' --verbose --parallel 4
    - name: 'Test'
      run: ${{ matrix.sanitizer.run_flags }} ctest --test-dir 'build' --timeout 10 --tests-regex 'kalman_(test|sample)' --verbose --parallel 4
