name: "Test Address: Sanitizer"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Install
      run: |
        ( cd /tmp
          git clone --depth 1 "https://gitlab.com/libeigen/eigen"
          cmake -S "eigen" -B "eigen/build"
          cmake --build "eigen/build" --parallel 4
          sudo cmake --install "eigen/build" )
        ( cd /tmp
          git clone --depth 1 "https://github.com/fmtlib/fmt"
          cmake -S "fmt" -B "fmt/build"
          cmake --build "fmt/build" --parallel 4
          sudo cmake --install "fmt/build" )
        ( cd /tmp
          git clone --depth 1 "https://github.com/kokkos/mdspan"
          cmake -S "mdspan" -B "mdspan/build"
          cmake --build "mdspan/build" --parallel 4
          sudo cmake --install "mdspan/build" )
        ( cd /tmp
          git clone --depth 1 "https://github.com/kokkos/stdblas"
          cmake -S "stdblas" -B "stdblas/build"
          cmake --build "stdblas/build" --parallel 4
          sudo cmake --install "stdblas/build" )
    - name: Build
      run: |
        gcc \
          sample/*.cpp test/*.cpp source/*.cpp \
          -Iinclude -I/usr/local/include/eigen3 -Isupport \
          -std=c++23 -g -fsanitize=address -fsanitize-address-use-after-scope -fno-omit-frame-pointer -lstdc++ -lm -lfmt
    - name: Test
      run: ASAN_OPTIONS=verbosity=2:strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1 ./a.out
