name: "Test Static Analysis: CppCheck"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
    - name: Install
      run: |
        ( cd /tmp ;
          git clone --depth 1 https://github.com/danmar/cppcheck.git ;
          ( cd cppcheck ;
            mkdir build ;
            ( cd build ; 
              cmake .. ; 
              cmake --build . ; 
              sudo make install ; ) ) )
    - name: Version
      run: cppcheck --version
    - name: Check
      run: cppcheck --verbose --error-exitcode=1 --enable=all -I include .
