name: "Test Static Analysis"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
    - name: Install
      run: |
        sudo apt update
        sudo apt install clang-tidy-14
        pip install cmakelang
        ( cd /tmp ;
          git clone --depth 1 https://gitlab.com/libeigen/eigen.git ;
          ( cd eigen ;
            mkdir build ;
            ( cd build ; 
              cmake .. ; 
              cmake --build . ;
              sudo make install ; ) ) )
        ( cd /tmp ;
          git clone --depth 1 https://github.com/fmtlib/fmt.git ;
          ( cd fmt ;
            mkdir build ;
            ( cd build ;
              CXX=clang++-14 cmake -DFMT_HEADER_ONLY=TRUE .. ;
              sudo make install ; ) ) )
        ( cd /tmp ;
          git clone --depth 1 https://github.com/danmar/cppcheck.git ;
          ( cd cppcheck ;
            mkdir build ;
            ( cd build ; 
              cmake .. ; 
              cmake --build . ; 
              sudo make install ; ) ) )
    - name: Verify CppCheck
      run: cppcheck --verbose --error-exitcode=1 --enable=all -I include .
    - name: Verify ClangTidy
      run: |
        FILES=`find . -iname *.hpp -o -iname *.tpp`
        clang-tidy-14 ${FILES} --warnings-as-errors=* -- -x c++ -Iinclude -I/usr/local/include/eigen3 -Isupport/include/fcarouge -DFMT_HEADER_ONLY -Wall -Wextra -pedantic -std=c++2b -stdlib=libc++ -lfmt
    - name: Verify CMakeLint
      run: cmake-lint CMakeLists.txt
