name: "Test: Ubuntu 22.04 GCC Trunk"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
    - name: Build
      run: |
        wget http://kayari.org/gcc-latest/gcc-latest.deb
        sudo dpkg -i gcc-latest.deb
        export CC=/opt/gcc-latest/bin/gcc
        export CXX=/opt/gcc-latest/bin/g++
        mkdir build
        cd build
        cmake ..
        cmake --build . --parallel
        ctest --tests-regex kalman --output-on-failure --parallel
        sudo cmake --install .
