name: "Test: Ubuntu 22.04 GCC"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
    - name: Build
      run: |
        cmake -B "build" .
        cmake --build "build" --parallel 8
        ctest --test-dir "build" --tests-regex "kalman_(test|sample)" --output-on-failure --parallel 8
        sudo cmake --install "build"
