name: "Test Static Analysis: ClangTidy"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Update
      run: sudo apt update
    - name: Install
      run: |
        sudo apt install clang-tidy-13
        ( cd /tmp ; mkdir eigen ;
          git clone --depth 1 https://gitlab.com/libeigen/eigen.git ;
          ( cd eigen ;
            mkdir build ) ;
          ( cd eigen/build ; 
            cmake .. ; 
            cmake --build . ;
            sudo make install ) )
    - name: Tidy
      run: |
        FILES=`find . -iname *.hpp`
        clang-tidy-13 ${FILES} \
          --warnings-as-errors=* \
          -- -x c++ -Wall -Wextra -pedantic -std=c++2b -Iinclude -I/usr/local/include/eigen3
