name: "Test: Ubuntu 22.04 GCC"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --parallel
        ctest --tests-regex kalman --output-on-failure --parallel
        sudo cmake --install .
