name: "Test Address: Sanitizer"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Update
      run: sudo apt update
    - name: Install
      run: |
        sudo apt install gcc-11 g++-11
        ( cd /tmp ; mkdir eigen ;
          git clone --depth 1 https://gitlab.com/libeigen/eigen.git ;
          ( cd eigen ;
            mkdir build ) ;
          ( cd eigen/build ; 
            cmake .. ; 
            cmake --build . ;
            sudo make install ) )
    - name: Build
      run: gcc-11 sample/*.cpp test/*.cpp source/*.cpp -Iinclude -I/usr/local/include/eigen3 -std=c++23 -g -fsanitize=address -fsanitize-address-use-after-scope -fno-omit-frame-pointer -lstdc++ -lm
    - name: Test
      run: ASAN_OPTIONS=verbosity=2:strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1 ./a.out
