name: "Test: Windows 2019 MSVC"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install
      uses: ilammy/msvc-dev-cmd@v1.10.0
    - name: Install Eigen
      run: vcpkg install eigen3
    - name: Build
      run: cl /EHsc /std:c++latest /I include /I C:\vcpkg\packages\eigen3_x86-windows\include\eigen3 /TP sample/*.cpp source/*.cpp test/*.cpp /Fe:kalman.exe
    - name: Run
      run: ./kalman.exe
