name: "Test Memory: Valgrind"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
    - name: Update
      run: sudo apt update
    - name: Install
      run: |
        sudo apt install gcc-12 g++-12 valgrind
        ( cd /tmp ;
          git clone --depth 1 https://gitlab.com/libeigen/eigen.git ;
          ( cd eigen ;
            mkdir build ;
            ( cd build ; 
              cmake .. ; 
              cmake --build . ;
              sudo make install ; ) ) )
        ( cd /tmp ;
          git clone --depth 1 https://github.com/fmtlib/fmt.git ;
          ( cd fmt ;
            mkdir build ;
            ( cd build ;
              cmake .. ;
              sudo make install ; ) ) )
    - name: Build
      run: |
        gcc-12 \
          sample/*.cpp test/*.cpp source/*.cpp \
          -Iinclude -I/usr/local/include/eigen3 -Isupport/include/fcarouge \
          -g -O0 -std=c++23 -lstdc++ -lm -lfmt
    - name: Test
      run: valgrind --verbose ./a.out
