name: "Test: Windows 2019 MSVC"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
    - name: Install
      uses: ilammy/msvc-dev-cmd@v1.10.0
    - name: Version
      run: cl
    - name: Build
      run: |
        cmake -B "build" .
        cmake --build "build" --parallel 8
        ctest --test-dir "build" --tests-regex "kalman_(test|sample)" --output-on-failure --parallel 8
